import Link from "next/link";
import { redirect } from "next/navigation";
import BCPOutsourcedProcessControl from "../../../../components/BCPOutsourcedProcessControl";
import { createClient } from "../../../../lib/supabase/server";
import { saveOutsourcedProcesses } from "./actions";

export const metadata={title:"Outsourced Process & Supply Chain Control | RPG Excellence"};
export const dynamic="force-dynamic";
export default async function OutsourcedProcessesPage({searchParams}){
  const params=await searchParams,s=await createClient(),{data:{user}}=await s.auth.getUser();if(!user)redirect("/portal/login?next=/portal/business-continuity/outsourced-processes");
  const{data:org}=await s.from("organizations").select("id,name").eq("owner_id",user.id).order("created_at").limit(1).maybeSingle();let profiles=[],contexts=[],roles=[],hazards=[],bias=[],initial=null;
  if(org){const fetch=(table)=>s.from(table).select("*").eq("organization_id",org.id).neq("status","archived").order("updated_at",{ascending:false});const results=await Promise.all([fetch("bcp_site_profiles"),fetch("bcp_context_assessments"),fetch("bcp_role_assessments"),fetch("bcp_hazard_assessments"),fetch("bcp_bia_assessments")]);[profiles,contexts,roles,hazards,bias]=results.map((x)=>x.data||[]);if(params?.new!=="1"){let q=s.from("bcp_outsourced_process_assessments").select("*").eq("organization_id",org.id).neq("status","archived");if(params?.id)q=q.eq("id",params.id);({data:initial}=await q.order("updated_at",{ascending:false}).limit(1).maybeSingle())}}
  return <main style={{minHeight:"100vh",padding:"26px 2vw 80px",background:"#edf3f8",fontFamily:"Arial,sans-serif"}}><div style={{maxWidth:1840,margin:"auto"}}><header style={{display:"flex",justifyContent:"space-between",gap:20,marginBottom:20}}><div><small style={{color:"#6845d1",fontWeight:900,letterSpacing:".1em"}}>BCP HUB · MODULE 7 · ISO 22301 CLAUSE 8.1</small><h1 style={{margin:"7px 0",color:"#071d3a",fontSize:42}}>Outsourced Process &amp; Supply Chain Control</h1><p style={{margin:0,color:"#62788e"}}>Connect priority activities and recovery objectives to supplier controls, continuity capability, performance and accountable improvement.</p></div><div style={{display:"flex",gap:8}}><Link href="/portal/business-continuity/outsourced-processes?new=1" style={{padding:"11px 14px",borderRadius:8,background:"#315fe6",color:"#fff",textDecoration:"none",fontWeight:850}}>+ New assessment</Link><Link href="/portal/business-continuity" style={{padding:"11px 14px",border:"1px solid #c5d3e0",borderRadius:8,background:"#fff",color:"#173b60",textDecoration:"none",fontWeight:850}}>← BCP Hub</Link></div></header><BCPOutsourcedProcessControl action={saveOutsourcedProcesses} profiles={profiles} contexts={contexts} roles={roles} hazards={hazards} bias={bias} initial={initial} organisationName={org?.name||""} startStep={params?.step||0}/></div></main>;
}
