import {notFound} from "next/navigation";
import HsInsightArticle from "../../../../components/HsInsightArticle";
import {locales} from "../../../../lib/i18n";

export const metadata={
  title:"Business Continuity Implementation Begins: Module 1 Released",
  description:"RPG Excellence begins a full business continuity implementation programme with a connected Site Profile Assessment and role-based ISO 22301 training.",
  alternates:{canonical:"/en/insights/business-continuity-implementation-module-1"},
  openGraph:{title:"Building Business Continuity as a Capability: Module 1 Released",description:"A connected implementation programme combining site profiling, operational mapping and ISO 22301 learning.",images:["/insights/business-continuity-module-1-launch.png"]},
};

const article={
  issue:"018",slug:"business-continuity-implementation-module-1",
  title:"Building Business Continuity as a Capability: Our Full Implementation Programme Begins",
  description:metadata.description,
  standfirst:"RPG Excellence has started the controlled rollout of a complete business continuity implementation pathway. The first module connects site profiling, operational mapping and role-based ISO 22301 learning so organisations can build capability from evidence—not from a blank plan template.",
  image:"/insights/business-continuity-module-1-launch.png",
  imageAlt:"Cross-functional leadership team mapping sites, services, dependencies and continuity priorities in an operations command centre",
  opening:"Business continuity is often approached backwards. A plan is drafted first, assumptions are added later, and training is delivered separately from the decisions people must make. Our new implementation pathway starts with the organisation itself: where it operates, what it must deliver, which processes create that value, what those processes depend on and who must be capable of responding.",
  roadmap:[
    ["01","Profile","Sites, services, processes and owners"],["02","Learn","Role-based ISO 22301 capability"],["03","Context","Interested parties and scope"],["04","Analyse","Disruption risk and BIA"],["05","Prepare","Strategies, plans and resources"],["06","Assure","Exercise, review and improve"],
  ],
  sections:[
    {heading:"Module 1 establishes the operational truth",paragraphs:["The Site Profile Assessment creates the controlled baseline for everything that follows. Rather than asking users to write broad descriptions, it structures the organisation into accountable sites, priority products and services, value-chain processes, support processes, dependencies, information assets and responsible roles.","That information is reusable. Later modules can draw from the same approved profile instead of asking teams to re-enter inconsistent versions of their operations."],points:["Define the accountable site boundary and leadership roles.","Identify priority products and services that must continue or recover.","Map value-chain and support processes with accountable owners.","Record people, premises, technology, information, supplier and utility dependencies.","Identify the initial population requiring continuity competence."]},
    {heading:"Training is embedded in implementation—not added at the end",paragraphs:["The first release includes a BCP learning pathway aligned with ISO 22301. Learning is connected to implementation phases so participants understand why information is required, how it will be used and which decisions they are expected to support.","This matters because a business continuity management system cannot be operated by one coordinator alone. Leaders approve priorities and resources; process owners validate impacts and dependencies; response teams need authority and competence; participants must understand escalation, communication and recovery responsibilities."],points:["Foundation learning for the purpose and structure of a BCMS.","Role-specific learning released alongside implementation activity.","Knowledge checks and retained evidence of completion.","A direct connection between competence, assigned responsibilities and implementation records."]},
    {heading:"The data chain starts here",paragraphs:["Module 1 is not an isolated questionnaire. It establishes the source data used by the wider continuity workflow. A priority service links to the processes that deliver it. Each process links to owners, outputs and dependencies. Those records then inform context analysis, risk assessment, business impact analysis, recovery strategy and exercising.","The result is traceability: management can follow a continuity decision back to the service, process, dependency, requirement and evidence that justified it."],points:["Product or service → value-chain process → critical activity.","Critical activity → dependency → disruption scenario.","Impact tolerance → recovery objective → continuity strategy.","Strategy → plan → exercise evidence → improvement action."]},
    {heading:"What comes next",paragraphs:["Module 3 will build on the site profile to assess internal and external context, relevant interested parties, continuity requirements, risk appetite and the scope of the BCMS. Dynamic prioritisation will help teams distinguish material continuity issues from background information.","The subsequent pathway will connect disruption risk, business impact analysis, continuity strategies, response structures, plans, exercises and continual improvement. Each module will use controlled data from the modules before it."],points:["Context and interested-party requirements.","Disruption-risk assessment and business impact analysis.","Continuity strategies, solutions and resource decisions.","Incident response, communication, recovery and return to normal.","Exercise programmes, performance evaluation and improvement."]},
    {heading:"A practical ISO 22301 implementation pathway",paragraphs:["ISO 22301 provides the management-system framework, but implementation still requires organisational judgement. Our approach uses the standard to structure the work while keeping decisions grounded in the organisation’s real services, processes, risks and operating constraints.","The objective is not to produce more documentation. It is to create a maintained capability that can explain what matters, make defensible priorities, organise an effective response and demonstrate learning over time."]},
  ],
  managementTest:"Can your continuity team trace every recovery priority back to an accountable service, process, dependency and management decision?",
  managementAnswer:"If the organisation cannot make that connection, its plans may contain recovery statements without a reliable operational basis. Module 1 creates the controlled foundation on which those later decisions depend.",
  productCopy:"The RPG Excellence Business Continuity Planning Hub now includes the Site Profile Assessment and its connected ISO 22301 learning pathway. The implementation workspace retains progress, reuses approved profile data across modules and produces structured inputs for context, disruption risk, BIA, strategy and planning.",
  productHref:"/portal/business-continuity",productLabel:"Open the Business Continuity Planning Hub",
};

export default async function Page({params}){const{locale}=await params;if(!locales.includes(locale))notFound();return <HsInsightArticle locale={locale} article={article}/>}
