import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {createClient} from "../../../../../lib/supabase/server";
import {saveCapaStage} from "./actions";

const META={
  correction:{title:"1. Correction and containment",guide:"Control the detected nonconformity, correct the immediate issue and assess whether similar outputs are affected.",prompt:"Describe the correction, containment, affected scope and confirmation that further escape is controlled."},
  cause_analysis:{title:"2. Cause and extent analysis",guide:"Use evidence to determine why the nonconformity occurred and whether it exists elsewhere. Match analytical depth to risk and recurrence.",prompt:"Record the evidence-supported cause, extent review and why the analysis is proportionate."},
  corrective_action:{title:"3. Corrective action",guide:"Define action that removes the cause, with an accountable owner, due date, resources and measurable effectiveness criteria.",prompt:"Describe the approved action, implementation result and the criterion that will demonstrate effectiveness."},
  effectiveness_review:{title:"4. Independent effectiveness review",guide:"After enough operating time, independently verify that action was implemented, the cause was controlled and recurrence has not occurred.",prompt:"Record the sample, monitoring period, result and independent conclusion. An ineffective result reopens corrective action."},
};
const pretty=v=>String(v||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default async function CapaCasePage({params}){
  const {id}=await params;
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();
  if(!user)redirect("/portal/login");
  const [{data:rcaCase,error},{data:stages,error:stageError}]=await Promise.all([
    supabase.from("rca_cases").select("*").eq("id",id).eq("owner_id",user.id).maybeSingle(),
    supabase.from("rca_capa_stages").select("*").eq("case_id",id).eq("owner_id",user.id).order("stage_order")
  ]);
  if(error)throw new Error(error.message); if(!rcaCase)notFound();
  if(rcaCase.case_type!=="capa")redirect(`/portal/rca/${id}`);
  if(stageError)throw new Error(stageError.message);
  const completed=(stages||[]).filter(row=>row.completed_at).length;
  const progress=Math.round(completed/4*100);
  return <main className="cap"><style>{`
    *{box-sizing:border-box}.cap{min-height:100vh;background:#edf3fa;color:#061a35;padding:28px clamp(16px,4vw,54px) 70px}.wrap{max-width:1320px;margin:auto}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;flex-wrap:wrap}.eyebrow{color:#155eef;font-weight:900;letter-spacing:.1em;font-size:12px}.top h1{font-size:clamp(32px,5vw,50px);margin:7px 0}.top p{color:#61758d}.back{padding:12px 15px;background:#fff;border:1px solid #cbd8e7;border-radius:10px;color:#061a35;text-decoration:none;font-weight:850}.hero{margin:24px 0;display:grid;grid-template-columns:1fr 260px;gap:22px;padding:27px;border-radius:20px;background:#082b56;color:#fff}.hero p{color:#c6d8ec;line-height:1.55}.meter{align-self:center}.bar{height:10px;background:#ffffff24;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:#51ded1}.meter strong{display:block;font-size:30px;margin-bottom:9px}.grid{display:grid;gap:16px}.card{padding:24px;border:1px solid #d5e1ed;border-left:5px solid #a8b8ca;border-radius:16px;background:#fff}.card.active{border-left-color:#155eef}.card.done{border-left-color:#0a9b69}.head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.head h2{margin:0 0 6px;font-size:21px}.guide{margin:0;color:#60758e;line-height:1.55}.state{white-space:nowrap;padding:7px 10px;border-radius:99px;background:#eef3f8;font-size:12px;font-weight:900}.form{display:grid;grid-template-columns:1fr 1fr;gap:13px;margin-top:18px}.wide{grid-column:1/-1}.field{display:grid;gap:7px;font-size:13px;font-weight:850}.field :is(input,textarea,select){width:100%;min-height:46px;padding:12px;border:1px solid #cbd8e7;border-radius:9px;background:#fff;font:inherit}.actions{display:flex;gap:10px}.btn{padding:12px 16px;border:0;border-radius:9px;background:#155eef;color:#fff;font-weight:900;cursor:pointer}.btn.secondary{background:#eaf0f8;color:#123}.locked{margin-top:15px;padding:13px;border-radius:9px;background:#f4f6f9;color:#6c7b8b}@media(max-width:720px){.hero,.form{grid-template-columns:1fr}.wide{grid-column:auto}}
  `}</style><div className="wrap"><header className="top"><div><div className="eyebrow">{rcaCase.case_reference} · CONTROLLED CAPA</div><h1>{rcaCase.title}</h1><p>{pretty(rcaCase.source_type)} · {pretty(rcaCase.severity)} · {pretty(rcaCase.status)}</p></div><div style={{display:"flex",gap:10}}>{rcaCase.assessment_id&&<Link className="back" href={`/portal/assessments/${rcaCase.assessment_id}/findings`}>Source assessment</Link>}<Link className="back" href="/portal/rca">CAPA–8D register</Link></div></header>
  <section className="hero"><div><h2 style={{marginTop:0}}>Proportionate corrective-action workflow</h2><p>This four-stage route maintains traceability from nonconformity through correction, cause, corrective action and independent effectiveness verification. Closure is permitted only after effectiveness is confirmed.</p></div><div className="meter"><strong>{progress}% complete</strong><div className="bar"><i style={{width:`${progress}%`}}/></div></div></section>
  <section className="grid">{(stages||[]).map((row,index)=>{const meta=META[row.stage];const previousComplete=index===0||stages[index-1]?.completed_at;const locked=!previousComplete;const done=Boolean(row.completed_at);return <article key={row.id} className={`card ${done?"done":rcaCase.capa_current_stage===row.stage?"active":""}`}><div className="head"><div><h2>{meta.title}</h2><p className="guide">{meta.guide}</p></div><span className="state">{done?"Completed":locked?"Locked":"Available"}</span></div>{locked?<div className="locked">Complete the preceding stage to unlock this controlled record.</div>:<form action={saveCapaStage} className="form"><input type="hidden" name="case_id" value={id}/><input type="hidden" name="stage" value={row.stage}/><label className="field wide">Controlled record<textarea name="narrative" required rows={4} defaultValue={row.narrative||""} placeholder={meta.prompt}/></label><label className="field">Objective evidence / reference<input name="evidence_reference" required defaultValue={row.evidence_reference||""} placeholder="File, record, ticket, audit sample or controlled link"/></label><label className="field">Due or review date<input name="due_date" type="date" defaultValue={row.due_date||""}/></label>{row.stage==="effectiveness_review"&&<label className="field wide">Effectiveness decision<select name="decision" required defaultValue={row.decision||""}><option value="">Select decision</option><option value="effective">Effective — criteria met; close CAPA</option><option value="ineffective">Ineffective — return to corrective action</option></select></label>}<div className="actions wide"><button className="btn secondary" name="intent" value="save">Save draft</button>{!done&&<button className="btn" name="intent" value="complete">Complete stage →</button>}</div></form>}</article>})}</section></div></main>;
}
