import { createHash } from "node:crypto";
import { notFound } from "next/navigation";
import { createAdminClient } from "../../../lib/supabase/admin";
import { submitExternalAuditAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function AuditActionOwnerPage({ params, searchParams }) {
  const { token } = await params;
  const query = await searchParams;
  const supabase = createAdminClient();
  const tokenHash = createHash("sha256").update(token).digest("hex");
  const { data: access, error } = await supabase.from("internal_audit_action_access").select("*, internal_audit_findings(finding_reference, finding_type, risk_level, title, failure_statement, criteria, objective_evidence, process_area, agreed_date), internal_audits(audit_reference, title)").eq("secure_token_hash", tokenHash).gt("secure_token_expires_at", new Date().toISOString()).maybeSingle();
  if (error || !access) notFound();
  const finding = access.internal_audit_findings;
  const audit = access.internal_audits;
  return <main className="ownerPage"><style>{`
    *{box-sizing:border-box}.ownerPage{min-height:100vh;padding:32px 18px 70px;background:#eef4fb;color:#061a35;font-family:Arial,sans-serif}.ownerShell{max-width:1050px;margin:auto}.ownerHead{padding:30px;border-radius:22px;background:linear-gradient(125deg,#061a35,#0b4477);color:#fff}.ownerHead small{color:#63e2dd;font-weight:900;text-transform:uppercase;letter-spacing:.1em}.ownerHead h1{margin:8px 0}.ownerHead p{margin:0;color:#d5e3f2}.notice{margin:18px 0;padding:15px 18px;border-radius:12px;background:#e8f8ef;color:#07613a;font-weight:800}.notice.error{background:#fff1e2;color:#844800}.card{margin-top:18px;padding:24px;border:1px solid #d5e1ed;border-radius:18px;background:#fff;box-shadow:0 15px 35px #061a3510}.locked{border-left:5px solid #1761e8}.locked h2{margin:6px 0}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.meta div{padding:13px;border-radius:10px;background:#f3f7fb}.meta b,.meta span{display:block}.meta span{margin-top:5px;color:#60758d}.grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.field{display:flex;flex-direction:column;gap:7px}.field span{font-size:13px;font-weight:850}.field textarea,.field input{width:100%;min-height:48px;padding:12px;border:1px solid #cbd8e6;border-radius:10px;font:inherit}.field textarea{min-height:120px;resize:vertical}.wide{grid-column:1/-1}.button{margin-top:18px;min-height:48px;padding:0 20px;border:0;border-radius:10px;background:#1761e8;color:#fff;font:inherit;font-weight:900;cursor:pointer}.control{margin-top:18px;padding:14px;border-radius:12px;background:#fff8e7;color:#6a4c08;line-height:1.5}@media(max-width:700px){.grid,.meta{grid-template-columns:1fr}.wide{grid-column:auto}}
  `}</style><div className="ownerShell">
    <header className="ownerHead"><small>Restricted corrective-action workspace</small><h1>{audit?.title || "Internal audit action"}</h1><p>{audit?.audit_reference} · Assigned to {access.assignee_name} · Link expires {new Intl.DateTimeFormat("en-GB", {dateStyle:"medium"}).format(new Date(access.secure_token_expires_at))}</p></header>
    {query?.submitted ? <div className="notice">Response submitted successfully. The auditor will review it and may accept it or return it for revision.</div> : null}
    {query?.error === "incomplete" ? <div className="notice error">Complete correction/containment, root cause, corrective-action plan and effectiveness measure before submitting.</div> : null}
    {query?.error === "file_size" ? <div className="notice error">The evidence file exceeds the 10 MB limit.</div> : null}
    <section className="card locked"><small>Auditor-controlled record — read only</small><h2>{finding?.finding_reference} · {finding?.title}</h2><div className="meta"><div><b>Classification</b><span>{finding?.finding_type?.replaceAll("_", " ")}</span></div><div><b>Risk</b><span>{finding?.risk_level}</span></div><div><b>Process</b><span>{finding?.process_area || "—"}</span></div></div><h3>Statement of nonconformity</h3><p>{finding?.failure_statement}</p><h3>Requirement</h3><p>{finding?.criteria}</p><h3>Objective evidence</h3><p>{finding?.objective_evidence}</p></section>
    <section className="card"><h2>Organisation response</h2><p>Provide a factual response addressing correction, cause, systemic extent, corrective action and how effectiveness will be demonstrated.</p><form action={submitExternalAuditAction}><input type="hidden" name="token" value={token} /><div className="grid"><label className="field"><span>Correction and immediate containment *</span><textarea name="correction_and_containment" required defaultValue={access.correction_and_containment || ""} /></label><label className="field"><span>Root-cause response *</span><textarea name="root_cause_response" required defaultValue={access.root_cause_response || ""} /></label><label className="field"><span>Extent and systemic review</span><textarea name="extent_and_systemic_review" defaultValue={access.extent_and_systemic_review || ""} /></label><label className="field"><span>Corrective-action plan *</span><textarea name="corrective_action_plan" required defaultValue={access.corrective_action_plan || ""} /></label><label className="field wide"><span>Effectiveness measure and acceptance criteria *</span><textarea name="effectiveness_measure" required defaultValue={access.effectiveness_measure || ""} /></label><label className="field"><span>Supporting evidence</span><input type="file" name="evidence_file" accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv,.docx,.xlsx" /></label><label className="field"><span>Evidence description</span><input name="evidence_description" /></label><label className="field wide"><span>Submission notes</span><textarea name="owner_submission_notes" defaultValue={access.owner_submission_notes || ""} /></label></div><button className="button">Submit Response to Auditor</button></form><div className="control"><strong>Controlled access:</strong> you cannot change the finding, classification, requirement or audit evidence. Submitting a response does not close the NC; effectiveness must be independently verified by the auditor.</div></section>
  </div></main>;
}
