"use client";

import { useActionState, useRef, useState } from "react";

const steps = ["Controlled sources", "Response teams", "Activation & escalation", "Warning & communications", "Incident Action Plan", "Recovery & approval"];
const arr = (value) => Array.isArray(value) ? value : [];
const fields = {
  teams: [["name", "Team / function"], ["leadPersonId", "Team leader", "person"], ["alternatePersonId", "Deputy", "person"], ["authority", "Decision authority", "authority"], ["responsibilities", "Responsibilities", "responsibilities"], ["procedure", "Procedural control", "long"]],
  thresholds: [["scenario", "Linked scenario", "readonly"], ["activationCriteria", "Activation criteria", "long"], ["initialControls", "Immediate protective actions", "long"], ["responseLevel", "Response level", "level"]],
  communications: [["audience", "Audience"], ["what", "Message / information", "long"], ["when", "Trigger and frequency"], ["primaryMethod", "Primary channel", "channel"], ["fallbackMethod", "Fallback channel", "channel"], ["ownerPersonId", "Communication owner", "person"], ["logMethod", "Communication record"]],
  actions: [["objective", "Response objective"], ["action", "Action", "long"], ["ownerPersonId", "Action owner", "person"], ["priority", "Priority", "priority"], ["status", "Status", "status"]],
};
const options = {
  authority: ["Activate the incident response", "Escalate to the incident controller", "Authorise evacuation and immediate protection", "Approve emergency expenditure", "Authorise recovery and operational handback"],
  responsibilities: ["Coordinate the incident response", "Protect people and account for personnel", "Maintain communications and stakeholder updates", "Restore priority processes and dependencies", "Coordinate supplier and technical support"],
  level: ["Local response", "Site incident", "Organisation crisis"],
  channel: ["Telephone", "SMS", "Email", "Teams / video call", "Public address", "In-person briefing", "Radio"],
  priority: ["Critical", "High", "Normal"], status: ["open", "in_progress", "closed"],
};
const recoveryFields = [["normalOperationsCriteria", "Criteria for returning to normal operations"], ["handbackAuthority", "Operational handback authority"], ["eocClosureCriteria", "Incident coordination centre closure criteria"], ["standDownProcess", "Stand-down and resource release"], ["employeeSupport", "Employee welfare and support"], ["postIncidentReview", "Post-incident review and improvement"], ["planAvailability", "Plan availability during an outage"]];
const blank = (type) => Object.fromEntries(fields[type].map(([key]) => [key, ""]));
const name = (person) => `${person.first_name || ""} ${person.last_name || ""}`.trim();

export default function BCPIncidentManagement({ action, profiles = [], contexts = [], roles = [], hazards = [], bias = [], strategies = [], people = [], initial, startStep = 0 }) {
  const [formState, formAction, pending] = useActionState(action, { error: "" });
  const formRef = useRef(null);
  const [step, setStep] = useState(Math.max(0, Math.min(5, Number(startStep) || 0)));
  const [sources, setSources] = useState({ site_profile_id: initial?.site_profile_id || "", context_assessment_id: initial?.context_assessment_id || "", role_assessment_id: initial?.role_assessment_id || "", hazard_assessment_id: initial?.hazard_assessment_id || "", bia_assessment_id: initial?.bia_assessment_id || "", strategy_assessment_id: initial?.strategy_assessment_id || "" });
  const [title, setTitle] = useState(initial?.assessment_title || "Incident Management, Response & Recovery");
  const [frequency, setFrequency] = useState(initial?.review_frequency || "Every 12 months");
  const [date, setDate] = useState(initial?.next_review_date || "");
  const [teams, setTeams] = useState(arr(initial?.response_teams));
  const [thresholds, setThresholds] = useState(arr(initial?.activation_thresholds));
  const [communications, setCommunications] = useState(arr(initial?.warning_communications));
  const [actions, setActions] = useState(arr(initial?.incident_action_plan));
  const [recovery, setRecovery] = useState(initial?.recovery_stand_down || {});
  const [approver, setApprover] = useState(initial?.approver_person_id || "");
  const [comment, setComment] = useState(initial?.review_comment || "");
  const hazard = hazards.find((row) => row.id === sources.hazard_assessment_id);
  const scenarios = arr(hazard?.scenario_assessments).filter((row) => row.includeInIncidentPlan !== false);
  const datasets = { teams: [teams, setTeams], thresholds: [thresholds, setThresholds], communications: [communications, setCommunications], actions: [actions, setActions] };
  const sourceSpecs = [["site_profile_id", "Module 1 · Site profile", profiles], ["context_assessment_id", "Module 3 · Context", contexts], ["role_assessment_id", "Module 4 · Roles", roles], ["hazard_assessment_id", "Module 5 · Hazard scenarios", hazards], ["bia_assessment_id", "Module 6 · Business impact analysis", bias], ["strategy_assessment_id", "Module 8 · Continuity strategies", strategies]];
  const completeRows = (type, rows) => rows.length > 0 && rows.every((row) => fields[type].every(([key]) => String(row[key] || "").trim()));
  const checks = [Boolean(sources.site_profile_id && sources.role_assessment_id && sources.hazard_assessment_id && sources.strategy_assessment_id), completeRows("teams", teams) && teams.every((row) => row.leadPersonId !== row.alternatePersonId), completeRows("thresholds", thresholds) && thresholds.every((row) => scenarios.some((s) => s.id === row.scenarioId)), completeRows("communications", communications), completeRows("actions", actions), recoveryFields.every(([key]) => String(recovery[key] || "").trim()) && Boolean(approver)];
  const percent = Math.round(checks.filter(Boolean).length / 6 * 100);
  const update = (type, index, key, value) => { const [rows, setter] = datasets[type]; setter(rows.map((row, i) => i === index ? { ...row, [key]: value } : row)); };
  const personSelect = (value, onChange) => <select value={value || ""} onChange={(event) => onChange(event.target.value)}><option value="">Select Company User</option>{people.map((person) => <option key={person.id} value={person.id}>{name(person)}</option>)}</select>;
  const rowEditor = (type) => {
    const [rows, setter] = datasets[type];
    return <>{rows.map((row, index) => <article key={row.id || index}><div className="rowHeading"><h3>{type === "thresholds" ? row.scenario : `${steps[step]} ${index + 1}`}</h3><button type="button" onClick={() => setter(rows.filter((_, i) => i !== index))}>Remove</button></div><div className="grid">{fields[type].map(([key, label, kind]) => <label key={key}>{label}{kind === "person" ? personSelect(row[key], (value) => update(type, index, key, value)) : kind === "long" ? <textarea value={row[key] || ""} onChange={(e) => update(type, index, key, e.target.value)} /> : options[kind] ? <><select value={options[kind].includes(row[key]) ? row[key] : ""} onChange={(e) => { const value = e.target.value; update(type, index, key, value); if (type === "teams" && key === "responsibilities" && !row.procedure) update(type, index, "procedure", `${value}. Follow the incident controller's instructions, confirm the assigned owner and deputy, record decisions and escalate when agreed limits are exceeded.`); }}><option value="">Choose a suggestion</option>{options[kind].map((value) => <option key={value}>{value}</option>)}</select><input aria-label={`${label} custom value`} value={row[key] || ""} onChange={(e) => update(type, index, key, e.target.value)} placeholder="Choose above or customise here" /></> : <input readOnly={kind === "readonly"} value={row[key] || ""} onChange={(e) => update(type, index, key, e.target.value)} />}</label>)}</div>{type === "teams" && row.leadPersonId && row.leadPersonId === row.alternatePersonId && <p className="error">Choose a different deputy to provide cover.</p>}</article>)}{type !== "thresholds" && <button type="button" className="add" onClick={() => setter([...rows, { ...blank(type), id: crypto.randomUUID() }])}>+ Add {type === "teams" ? "response team" : type === "communications" ? "communication control" : "action"}</button>}</>;
  };
  const savedId = formState.savedId || initial?.id || "";
  return <form ref={formRef} action={formAction} className="im">
    <input type="hidden" name="assessment_id" value={savedId} />
    <input type="hidden" name="next_step" value={Math.min(5, step + 1)} />
    {Object.entries(sources).map(([key, value]) => <input key={key} type="hidden" name={key} value={value} />)}
    {Object.entries({ assessment_title: title, review_frequency: frequency, next_review_date: date, approver_person_id: approver, review_comment: comment, response_teams: JSON.stringify(teams), activation_thresholds: JSON.stringify(thresholds), warning_communications: JSON.stringify(communications), incident_action_plan: JSON.stringify(actions), recovery_stand_down: JSON.stringify(recovery) }).map(([key, value]) => <input key={key} type="hidden" name={key} value={value} />)}
    <aside><h2>RPG Excellence</h2><small>BCP MODULE 9</small><h2>{percent}% complete</h2><progress value={percent} max="100" />{steps.map((label, index) => <button key={label} type="button" className={step === index ? "active" : ""} onClick={() => setStep(index)}>{checks[index] ? "✓" : index + 1} · {label}</button>)}<p>{thresholds.length} response scenarios<br />{teams.length} response teams<br />{actions.filter((row) => row.status !== "closed").length} open actions</p></aside>
    <section><header><small>STEP {step + 1} OF 6 · MODULE 9 · ISO 22301 CLAUSE 8.4</small><h2>{steps[step]}</h2><p>Connect assessed disruptions to the people, decisions and procedures needed to respond and recover.</p><b>{initial?.status?.replaceAll("_", " ") || "draft"}</b></header>
      {formState.error && <div className="error" role="alert">{formState.error}</div>}
      <div className="content">
      {step === 0 && <><p>Modules 1, 4, 5 and 8 are required. Link context and BIA where applicable. All linked records must be approved before approval of Module 9.</p><div className="grid">{sourceSpecs.map(([key, label, records]) => <label key={key}>{label}<select value={sources[key]} onChange={(event) => setSources({ ...sources, [key]: event.target.value })}><option value="">Select controlled record</option>{records.map((row) => <option key={row.id} value={row.id}>{row.assessment_reference || row.location_name || row.assessment_title} · v{row.version || 1} · {row.status}</option>)}</select></label>)}<label>Assessment title<input value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>Review frequency<select value={frequency} onChange={(e) => setFrequency(e.target.value)}>{["Quarterly", "Semi-annually", "Every 12 months", "After material change or incident"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Next review date<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label></div></>}
      {step === 1 && <><p>Assign a leader and a different deputy. Choose suggested authority and responsibility, then tailor the procedural control to the location.</p>{rowEditor("teams")}</>}
      {step === 2 && <><p>Select scenarios included in the linked Module 5 incident plan. Add the activation trigger and immediate protective actions for each selected scenario.</p>{!hazard && <p className="error">Select a Module 5 hazard assessment in Controlled sources first.</p>}<div className="cards">{scenarios.map((scenario) => { const selected = thresholds.some((row) => row.scenarioId === scenario.id); return <button type="button" key={scenario.id} className={selected ? "selected" : ""} onClick={() => setThresholds(selected ? thresholds.filter((row) => row.scenarioId !== scenario.id) : [...thresholds, { ...blank("thresholds"), scenarioId: scenario.id, scenario: scenario.name, activationCriteria: arr(scenario.warningIndicators).join("; "), initialControls: arr(scenario.existingControls).join("; "), responseLevel: "Site incident" }])}>{selected ? "✓ " : "+ "}{scenario.name}</button>; })}</div>{thresholds.some((row) => !scenarios.some((s) => s.id === row.scenarioId)) && <p className="error">A selected scenario is no longer included in this source. Remove it and select a current linked scenario.</p>}{rowEditor("thresholds")}</>}
      {step === 3 && <><p>Define who needs which information, when it is sent and how communication continues if the primary channel fails.</p>{rowEditor("communications")}</>}
      {step === 4 && <><p>Assign response objectives and actions to named owners. Track priority and progress through recovery.</p>{rowEditor("actions")}</>}
      {step === 5 && <><div className="grid">{recoveryFields.map(([key, label]) => <label key={key}>{label}<textarea value={recovery[key] || ""} onChange={(e) => setRecovery({ ...recovery, [key]: e.target.value })} /></label>)}<label>Approver{personSelect(approver, setApprover)}</label><label>Review / approval comment<textarea value={comment} onChange={(e) => setComment(e.target.value)} /></label></div><article><h3>Readiness summary</h3>{steps.map((label, index) => <p key={label}>{checks[index] ? "✓ Complete" : "Requires attention"} · {label}</p>)}</article></>}
      </div><footer><button type="button" disabled={pending || step === 0} onClick={() => setStep(step - 1)}>← Back</button><button disabled={pending} name="intent" value="draft">Save draft</button>{step < 5 && <button disabled={pending} name="intent" value="continue">Save & continue →</button>}<button disabled={pending} name="intent" value="review">Submit for review</button><button disabled={pending} className="primary" name="intent" value="approve">Approve controlled version</button>{savedId && <button disabled={pending} name="intent" value="archive">Archive</button>}</footer>
    </section>
    <style jsx>{`
      .im{display:grid;grid-template-columns:270px minmax(0,1fr);border:1px solid #c9d8e7;border-radius:18px;overflow:hidden;color:#0c2845;background:#fff}.im aside{background:#0c2845;color:white;padding:28px 20px}.im aside small{color:#46e1d2;letter-spacing:.15em;font-weight:900}.im aside button{display:block;width:100%;text-align:left;margin:12px 0;background:#163c60;color:white;border-color:#315374}.im aside button.active{background:#24568a;border-color:#64dcda}.im progress{width:100%;accent-color:#31c3b9}.im header{padding:28px;border-bottom:4px solid #28b8ba;background:#f5f9fe}.im header small{color:#315fe6;font-weight:900}.im h2{margin:12px 0;font-size:28px}.im p{line-height:1.55}.im .content{padding:26px}.im .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.im label{display:flex;flex-direction:column;gap:9px;font-size:16px;font-weight:750}.im input,.im select,.im textarea{box-sizing:border-box;width:100%;font:inherit;font-weight:400;color:#143556;padding:13px;border:1px solid #b7cbdf;border-radius:9px;background:#fff}.im select{background:#eef5ff}.im textarea{min-height:130px;resize:vertical;line-height:1.5}.im article{padding:22px;margin:0 0 22px;border:1px solid #c7d8e9;border-radius:12px;background:#fafcff}.im .rowHeading{display:flex;justify-content:space-between;align-items:center;gap:15px}.im button{font:inherit;font-weight:750;padding:12px 16px;border-radius:9px;border:1px solid #b7cbdf;background:#fff;color:#183f66;cursor:pointer}.im button:disabled{opacity:.5;cursor:wait}.im .primary,.im .add{background:#315fe6;color:#fff;border-color:#315fe6}.im footer{display:flex;flex-wrap:wrap;gap:10px;padding:22px;border-top:1px solid #c9d8e7}.im .error{padding:16px;background:#fff0ef;border:1px solid #edaaa5;border-radius:9px;color:#a6241c;margin:16px}.im .cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-bottom:24px}.im .cards button{text-align:left;min-height:70px}.im .cards button.selected{background:#dcf7f1;border-color:#14afa0;color:#086254}@media(max-width:900px){.im{grid-template-columns:1fr}.im aside{padding:20px}.im aside button{display:inline-block;width:auto;margin:5px}.im .grid,.im .cards{grid-template-columns:1fr}.im .content,.im header{padding:18px}}
    `}</style>
  </form>;
}
