import Link from "next/link";

function MenuLink({ href, active, children }) {
  return <Link href={href} className={`iswsLink ${active ? "active" : ""}`}><i aria-hidden="true"/><span>{children}</span></Link>;
}

function SubLink({ href, active, children }) {
  return <Link href={href} className={`iswsSubLink ${active ? "active" : ""}`}>{children}</Link>;
}

export default function ISMSWorkspaceShell({ active, children }) {
  const riskActive = active === "risk";
  const soaActive = ["soa", "soa-board", "soa-report"].includes(active);
  return <div className="iswsShell"><style>{`
    *{box-sizing:border-box}.iswsShell{display:grid;grid-template-columns:238px minmax(0,1fr);min-height:100vh;background:#edf3f8}.iswsSide{position:sticky;top:0;height:100vh;padding:28px 20px 22px;background:linear-gradient(180deg,#06264d,#071c38);color:#d7e5f4;display:flex;flex-direction:column;z-index:40}.iswsBrand{margin:0 10px 35px;color:#fff;font:950 25px Arial,sans-serif;text-decoration:none}.iswsBrand span{font-weight:400}.iswsCaption{margin:0 13px 12px;color:#7899ba;font:900 10px Arial,sans-serif;letter-spacing:.12em;text-transform:uppercase}.iswsNav{display:grid;gap:7px}.iswsLink{display:flex;align-items:center;gap:12px;padding:13px 14px;border-radius:10px;color:#c9d9ea;text-decoration:none;font:760 14px Arial,sans-serif}.iswsLink:hover,.iswsLink.active{background:#174e86;color:#fff}.iswsLink i{width:12px;height:12px;border:1px solid currentColor;border-radius:3px}.iswsLink.active i{background:#55ded2;border-color:#55ded2;box-shadow:inset 0 0 0 3px #174e86}.iswsSub{margin:-2px 0 5px 29px;padding-left:13px;border-left:1px solid #55728f}.iswsSubLink{display:block;padding:8px 10px;border-radius:8px;color:#9fbad3;text-decoration:none;font:800 12px Arial,sans-serif}.iswsSubLink:hover,.iswsSubLink.active{background:#0d3968;color:#62e1d7}.iswsNote{margin-top:auto;padding:18px;border:1px solid #ffffff1d;border-radius:14px;background:#ffffff09;font-family:Arial,sans-serif}.iswsNote strong,.iswsNote small{display:block}.iswsNote small{margin-top:6px;color:#9eb4cb;line-height:1.45}.iswsWork{min-width:0}@media(max-width:1050px){.iswsShell{grid-template-columns:78px minmax(0,1fr)}.iswsSide{padding:24px 10px}.iswsBrand{font-size:0;margin:0 0 26px;text-align:center}.iswsBrand:first-letter{font-size:24px}.iswsCaption,.iswsNote,.iswsSub{display:none}.iswsLink{justify-content:center;font-size:0}.iswsLink i{width:15px;height:15px}}@media(max-width:700px){.iswsShell{display:block}.iswsSide{position:static;height:auto;padding:16px 20px}.iswsBrand{display:block;font-size:21px;text-align:left;margin:0}.iswsBrand:first-letter{font-size:inherit}.iswsNav,.iswsCaption,.iswsNote{display:none}}
  `}</style><aside className="iswsSide"><Link href="/portal" className="iswsBrand">RPG <span>Excellence</span></Link><div className="iswsCaption">ISMS workspace</div><nav className="iswsNav"><MenuLink href="/portal">Dashboard</MenuLink><MenuLink href="/portal/information-security" active={active === "hub"}>ISMS Hub</MenuLink><MenuLink href="/portal/information-security/risk-management" active={riskActive}>Risk Management</MenuLink>{riskActive&&<div className="iswsSub"><SubLink href="/portal/information-security/risk-management" active>Risk Register &amp; assessments</SubLink></div>}<MenuLink href="/portal/soa" active={soaActive}>Statement of Applicability</MenuLink>{soaActive&&<div className="iswsSub"><SubLink href="/portal/soa" active={active === "soa"}>SoA Register</SubLink><SubLink href="/portal/soa/management-board" active={active === "soa-board"}>Management Board</SubLink><SubLink href="/portal/soa/management-board/executive-report" active={active === "soa-report"}>Executive Report</SubLink></div>}<MenuLink href="/portal/documents">Evidence</MenuLink><MenuLink href="/portal/reports">Reports</MenuLink></nav><div className="iswsNote"><strong>ISO/IEC 27001 workspace</strong><small>Connect risks, treatment decisions, Annex A controls, evidence and management oversight.</small></div></aside><div className="iswsWork">{children}</div></div>;
}
