"use client";
import {useMemo,useState} from "react";

const screening=[
  "Could the change increase risk to people, equipment or the environment?","Could the change reduce performance or reliability?",
  "Could the change affect mechanical, electrical, hydraulic or structural integrity?","Could the change negatively affect product or service quality, including delivery?",
  "Could the change negatively affect the customer, availability or downtime?","Could the change affect statutory, regulatory or legal compliance?"
];
const types={
  new_equipment:["Will installation introduce new hazards?","Are new procedures, drawings or process-safety information required?","Is operator training required?","Could regulatory compliance be affected?"],
  replace_equipment:["Will operating parameters change?","Are safety controls or interlocks different?","Could production or delivery be affected?"],
  remove_equipment:["Could removal affect process safety or continuity?","Are alternative systems required?","Could compliance be affected?"],
  move_machinery:["Could safety zones or emergency access be affected?","Could the production workflow be affected?","Are utilities or services affected?"],
  process_change:["Could safety, environment or equipment integrity be affected?","Are new procedures, SOPs or training required?","Will operating parameters change?"],
  cell_area_change:["Could nearby operations or personnel be affected?","Are exits, alarms or interlocks affected?","Are equipment or process adjustments required?"],
  new_chemical:["Is the chemical hazardous?","Is new PPE or training required?","Is an SDS, COSHH assessment or regulatory submission required?"],
  contractor_safety:["Will contractors work in a hazardous area?","Are permits or authorisations required?","Could operational schedules be affected?"],
  emergency_preparedness:["Could emergency response or evacuation routes be affected?","Are additional drills or training required?","Are fire protection, alarms or shutdown systems affected?"],
  environmental_management:["Could emissions, effluent, resource use or waste be affected?","Are environmental permits or legal approvals required?","Is new monitoring or control equipment required?"],
  other:["Could the change introduce a new or changed hazard?","Are controlled documents or training affected?","Is specialist or regulatory review required?"]
};
const impacts=["Health & safety","Environment","Engineering / integrity","Operations / continuity","Quality / product conformity","Customer / delivery","Legal / regulatory","Information security","Emergency arrangements","Training / competence","Documents / drawings","Contractor control"];
const nice=value=>value.replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase());
export default function MocInitiationForm({action,assessments=[],today}){
 const [screen,setScreen]=useState(Object.fromEntries(screening.map(q=>[q,"no"]))),[type,setType]=useState("new_equipment"),[path,setPath]=useState({}),[impact,setImpact]=useState([]),[duration,setDuration]=useState("permanent"),[risk,setRisk]=useState("low");
 const pathway=useMemo(()=>Object.values(screen).includes("yes")?"full":"lite",[screen]);const pssr=["high"].includes(risk)||["new_equipment","replace_equipment","remove_equipment","move_machinery","process_change"].includes(type)&&Object.values(path).includes("yes");
 const setAnswer=(setter,q,v)=>setter(current=>({...current,[q]:v}));const toggle=value=>setImpact(current=>current.includes(value)?current.filter(x=>x!==value):[...current,value]);
 return <form action={action} className="mcForm"><input type="hidden" name="screening_answers" value={JSON.stringify(screening.map(question=>({question,answer:screen[question]})))}/><input type="hidden" name="pathway" value={pathway}/><input type="hidden" name="path_answers" value={JSON.stringify((types[type]||[]).map(question=>({question,answer:path[question]||"no"})))}/><input type="hidden" name="impact_areas" value={JSON.stringify(impact)}/><input type="hidden" name="pssr_required" value={String(pssr)}/>
 <style>{`.mcForm{display:grid;gap:16px}.mcCard{padding:22px;border:1px solid #d4e1ea;border-radius:16px;background:#fff}.mcHead{display:flex;gap:12px;align-items:center;margin-bottom:17px}.mcHead i{display:grid;place-items:center;width:37px;height:37px;border-radius:10px;background:#087f6c;color:#fff;font-style:normal;font-weight:950}.mcHead h2{margin:0;font-size:21px}.mcHead p{margin:4px 0 0;color:#657b91}.mcGrid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.mcField{display:grid;gap:6px}.mcField.full{grid-column:1/-1}.mcField label,.mcLabel{font-size:12px;font-weight:900;color:#294964}.mcField input,.mcField select,.mcField textarea{width:100%;padding:12px;border:1px solid #c9d7e3;border-radius:9px;background:#fff;font:inherit}.mcQuestion{display:grid;grid-template-columns:minmax(0,1fr) 80px 80px;border-top:1px solid #e2e9ef}.mcQuestion>span{padding:13px 5px}.mcChoice{display:grid;place-items:center;border-left:1px solid #e2e9ef;font-size:11px;font-weight:850}.mcChoice input{accent-color:#087f6c}.mcPath{margin-top:14px;padding:15px;border-radius:11px;background:#f0f5f8}.mcPath strong{display:block;margin-bottom:8px}.mcImpacts{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:8px}.mcImpact{display:flex;gap:8px;padding:11px;border:1px solid #d5e1e9;border-radius:9px;font-size:12px;font-weight:800}.mcImpact input{accent-color:#087f6c}.mcBanner{padding:17px;border-left:5px solid #1762ef;border-radius:11px;background:#eaf2ff}.mcBanner.full{border-color:#cf5a22;background:#fff2e9}.mcBanner strong,.mcBanner span{display:block}.mcBanner strong{font-size:19px}.mcBanner span{margin-top:5px;color:#5f7589}.mcSubmit{position:sticky;bottom:12px;display:flex;justify-content:space-between;align-items:center;gap:15px;padding:17px 20px;border-radius:14px;background:#082a54;color:#fff;box-shadow:0 16px 40px #082a5440}.mcSubmit strong,.mcSubmit span{display:block}.mcSubmit span{margin-top:4px;color:#c7d8e8;font-size:12px}.mcSubmit button{padding:13px 18px;border:0;border-radius:9px;background:#0aae79;color:#fff;font-weight:950;cursor:pointer}@media(max-width:760px){.mcGrid,.mcImpacts{grid-template-columns:1fr}.mcField.full{grid-column:auto}.mcQuestion{grid-template-columns:minmax(0,1fr) 58px 58px}.mcSubmit{position:static;display:grid}}`}</style>
 <section className="mcCard"><div className="mcHead"><i>1</i><div><h2>Request and identify the change</h2><p>Define exactly what will be modified, added, removed or replaced.</p></div></div><div className="mcGrid"><div className="mcField full"><label>Change title *</label><input name="title" required minLength={4}/></div><div className="mcField"><label>Requestor *</label><input name="requestor_name" required/></div><div className="mcField"><label>Department *</label><select name="department" required>{["Production","Engineering","HSE","Quality","Maintenance","Facilities","Training","IT","Other"].map(x=><option key={x}>{x}</option>)}</select></div><div className="mcField"><label>Date requested *</label><input type="date" name="date_requested" defaultValue={today} required/></div><div className="mcField"><label>Affected area / cell *</label><input name="affected_area" required/></div><div className="mcField"><label>Change type *</label><select name="change_type" value={type} onChange={e=>{setType(e.target.value);setPath({});}}>{Object.keys(types).map(x=><option value={x} key={x}>{nice(x)}</option>)}</select></div><div className="mcField"><label>Temporary or permanent *</label><select name="duration_type" value={duration} onChange={e=>setDuration(e.target.value)}><option value="permanent">Permanent</option><option value="temporary">Temporary</option></select></div>{duration==="temporary"&&<div className="mcField"><label>Temporary change end date *</label><input type="date" name="temporary_end_date" required/></div>}<div className="mcField"><label>Equipment ID / name</label><input name="equipment_id"/></div><div className="mcField"><label>New chemical introduced?</label><select name="new_chemical"><option value="false">No</option><option value="true">Yes</option></select></div><div className="mcField full"><label>Detailed change description *</label><textarea name="change_description" required minLength={40} rows={5} placeholder="Describe the current state, proposed state, justification, operating parameters, safety systems, chemicals, document and training changes, regulatory/environmental impacts and implementation boundaries."/></div></div></section>
 <section className="mcCard"><div className="mcHead"><i>2</i><div><h2>Screen the change</h2><p>Any Yes answer automatically requires the Full MOC pathway.</p></div></div>{screening.map(q=><div className="mcQuestion" key={q}><span>{q}</span>{["yes","no"].map(v=><label className="mcChoice" key={v}><input type="radio" checked={screen[q]===v} onChange={()=>setAnswer(setScreen,q,v)}/>{v.toUpperCase()}</label>)}</div>)}<div className={`mcBanner ${pathway}`} style={{marginTop:14}}><strong>{pathway==="full"?"Full MOC required":"MOC Lite pathway"}</strong><span>{pathway==="full"?"HSE gate verification, risk review and relevant functional approvals are required.":"All screening answers are No. Proportionate approval and close-out controls still apply."}</span></div></section>
 <section className="mcCard"><div className="mcHead"><i>3</i><div><h2>Change-type pathway</h2><p>Answer the questions released by the selected change type.</p></div></div><div className="mcPath"><strong>{nice(type)}</strong>{types[type].map(q=><div className="mcQuestion" key={q}><span>{q}</span>{["yes","no"].map(v=><label className="mcChoice" key={v}><input type="radio" checked={(path[q]||"no")===v} onChange={()=>setAnswer(setPath,q,v)}/>{v.toUpperCase()}</label>)}</div>)}</div><div style={{height:16}}/><span className="mcLabel">Potential impact areas *</span><div className="mcImpacts">{impacts.map(x=><label className="mcImpact" key={x}><input type="checkbox" checked={impact.includes(x)} onChange={()=>toggle(x)}/>{x}</label>)}</div></section>
 <section className="mcCard"><div className="mcHead"><i>4</i><div><h2>Risk and implementation planning</h2><p>Establish assessment, hazard review, actions and target implementation.</p></div></div><div className="mcGrid"><div className="mcField"><label>Change risk level *</label><select name="risk_level" value={risk} onChange={e=>setRisk(e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div><div className="mcField"><label>Linked controlled risk assessment</label><select name="linked_assessment_id"><option value="">Not linked</option>{assessments.map(a=><option value={a.id} key={a.id}>{a.assessment_reference} — {a.title}</option>)}</select></div><div className="mcField"><label>Hazard analysis required?</label><select name="hazard_analysis_required"><option value="false">No</option><option value="true">Yes</option></select></div><div className="mcField"><label>Hazard analysis type</label><select name="hazard_analysis_type"><option value="">Not selected</option><option>HAZOP</option><option>What-If</option><option>LOPA</option><option>Task Risk Assessment</option></select></div><div className="mcField"><label>Target implementation date *</label><input type="date" name="target_date" required/></div><div className="mcField"><label>PSSR requirement</label><input value={pssr?"Required before implementation":"Not automatically required"} readOnly/></div><div className="mcField full"><label>Implementation plan *</label><textarea name="implementation_plan" required minLength={20} rows={4} placeholder="Sequence, ownership, resources, document changes, training, communication, commissioning and contingency arrangements."/></div></div></section>
 <footer className="mcSubmit"><div><strong>{pathway==="full"?"Create Full MOC":"Create MOC Lite"}</strong><span>The record will enter screening complete and await HSE gate verification.</span></div><button type="submit" disabled={!impact.length}>Create controlled change</button></footer></form>;
}
