"use client";

import { useMemo, useState } from "react";

const permitTypes=[
  ["hot_work","Hot work","Flame, heat, sparks or ignition"],["confined_space","Confined space","Restricted access or hazardous atmosphere"],
  ["electrical","Electrical work","Electrical isolation or live systems"],["work_at_height","Work at height","Work where a fall could cause injury"],
  ["excavation","Excavation","Ground disturbance or buried services"],["lifting","Lifting operation","Cranes, hoists or suspended loads"],["general","General permit","Other controlled high-risk work"],
];
const hazardOptions=["Fire or explosion","Hazardous atmosphere","Stored energy","Electricity","Work at height","Falling objects","Moving plant or vehicles","Excavation or ground collapse","Hazardous substances","Pressure or vacuum","Lifting operations","Restricted access or escape","Simultaneous operations","Other"];
const precautionOptions=["Approved risk assessment and method statement","Area inspected and boundaries confirmed","Isolation and lock-off verified","Services identified and protected","Atmosphere tested and monitoring arranged","Ventilation provided","Fire watch and extinguishers available","Access and rescue arrangements confirmed","Fall prevention or protection in place","Lifting plan and equipment verified","PPE specified and available","Adjacent work coordinated","Emergency arrangements briefed","Work party briefed and competent"];

export default function PermitToWorkForm({action,assessments=[],now,until}){
  const [type,setType]=useState("hot_work"),[hazards,setHazards]=useState([]),[precautions,setPrecautions]=useState([]);
  const toggle=(setter,value)=>setter(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value]);
  const readiness=useMemo(()=>hazards.length>0&&precautions.length>=3,[hazards,precautions]);
  return <form action={action} className="ptwForm">
    <input type="hidden" name="hazards" value={JSON.stringify(hazards)}/><input type="hidden" name="precautions" value={JSON.stringify(precautions)}/>
    <style>{`.ptwForm{display:grid;gap:16px}.ptwCard{padding:22px;border:1px solid #d4e1ea;border-radius:16px;background:#fff}.ptwHead{display:flex;gap:12px;align-items:center;margin-bottom:17px}.ptwHead i{display:grid;place-items:center;width:37px;height:37px;border-radius:10px;background:#087f6c;color:#fff;font-style:normal;font-weight:950}.ptwHead h2{margin:0;font-size:21px}.ptwHead p{margin:4px 0 0;color:#657b91}.ptwTypes{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.ptwType{padding:13px;border:1px solid #cfdae4;border-radius:10px;cursor:pointer}.ptwType.on{border-color:#087f6c;background:#eaf8f3;box-shadow:inset 0 0 0 1px #087f6c}.ptwType input{margin-right:7px;accent-color:#087f6c}.ptwType strong,.ptwType span{display:block}.ptwType span{margin:4px 0 0 22px;color:#687f93;font-size:11px}.ptwGrid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.ptwField{display:grid;gap:6px}.ptwField.full{grid-column:1/-1}.ptwField label,.ptwLabel{font-size:12px;font-weight:900;color:#294964}.ptwField input,.ptwField select,.ptwField textarea{width:100%;padding:12px;border:1px solid #c9d7e3;border-radius:9px;background:#fff;font:inherit}.ptwOptions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}.ptwOption{display:flex;gap:9px;align-items:center;padding:11px;border:1px solid #d5e1e9;border-radius:9px;font-size:12px;font-weight:800}.ptwOption input{accent-color:#087f6c}.ptwDeclaration{display:flex;gap:9px;align-items:flex-start;padding:13px;border-radius:10px;background:#f0f5f8;font-size:12px;line-height:1.45}.ptwDeclaration input{margin-top:2px;accent-color:#087f6c}.ptwSubmit{position:sticky;bottom:12px;display:flex;justify-content:space-between;align-items:center;gap:15px;padding:17px 20px;border-radius:14px;background:#082a54;color:#fff;box-shadow:0 16px 40px #082a5440}.ptwSubmit strong,.ptwSubmit span{display:block}.ptwSubmit span{margin-top:4px;color:#c7d8e8;font-size:12px}.ptwSubmit button{padding:13px 18px;border:0;border-radius:9px;background:#0aae79;color:#fff;font-weight:950;cursor:pointer}.ptwSubmit button:disabled{background:#6d8192;cursor:not-allowed}@media(max-width:760px){.ptwTypes,.ptwGrid,.ptwOptions{grid-template-columns:1fr}.ptwField.full{grid-column:auto}.ptwSubmit{position:static;display:grid}}`}</style>
    <section className="ptwCard"><div className="ptwHead"><i>1</i><div><h2>Define the controlled work</h2><p>Select the permit category and establish a clear scope.</p></div></div><div className="ptwTypes">{permitTypes.map(([value,label,detail])=><label className={`ptwType ${type===value?"on":""}`} key={value}><input type="radio" name="permit_type" value={value} checked={type===value} onChange={()=>setType(value)}/><strong>{label}</strong><span>{detail}</span></label>)}</div><div className="ptwGrid" style={{marginTop:15}}><div className="ptwField full"><label>Task description *</label><textarea name="task_description" required minLength={10} placeholder="Describe the exact work covered and its limits."/></div><div className="ptwField"><label>Site / location *</label><input name="site_location" required/></div><div className="ptwField"><label>Work area</label><input name="work_area"/></div><div className="ptwField"><label>Equipment / asset</label><input name="equipment_asset"/></div><div className="ptwField"><label>Contractor / company</label><input name="contractor_company"/></div><div className="ptwField full"><label>Linked approved risk assessment *</label><select name="linked_assessment_id" required><option value="">Select controlled assessment</option>{assessments.map(item=><option value={item.id} key={item.id}>{item.assessment_reference} — {item.title}</option>)}</select></div></div></section>
    <section className="ptwCard"><div className="ptwHead"><i>2</i><div><h2>Identify hazards and controls</h2><p>Record what makes the work hazardous and verify the precautions in place.</p></div></div><span className="ptwLabel">Hazards present *</span><div className="ptwOptions">{hazardOptions.map(item=><label className="ptwOption" key={item}><input type="checkbox" checked={hazards.includes(item)} onChange={()=>toggle(setHazards,item)}/>{item}</label>)}</div><div style={{height:16}}/><span className="ptwLabel">Precautions verified * (minimum three)</span><div className="ptwOptions">{precautionOptions.map(item=><label className="ptwOption" key={item}><input type="checkbox" checked={precautions.includes(item)} onChange={()=>toggle(setPrecautions,item)}/>{item}</label>)}</div><div className="ptwGrid" style={{marginTop:15}}><div className="ptwField full"><label>Isolations and lock-off details</label><textarea name="isolations" placeholder="Isolation points, lock numbers, test-for-dead or zero-energy verification."/></div><div className="ptwField full"><label>Emergency and rescue arrangements *</label><textarea name="emergency_arrangements" required placeholder="Alarm, communications, rescue equipment, responsible people and emergency contacts."/></div></div></section>
    <section className="ptwCard"><div className="ptwHead"><i>3</i><div><h2>Authorisation and validity</h2><p>Define the permit window and record acceptance by both parties.</p></div></div><div className="ptwGrid"><div className="ptwField"><label>Valid from *</label><input type="datetime-local" name="valid_from" defaultValue={now} required/></div><div className="ptwField"><label>Valid until *</label><input type="datetime-local" name="valid_until" defaultValue={until} required/></div><div className="ptwField"><label>Permit issuer *</label><input name="issuer_name" required/></div><div className="ptwField"><label>Permit receiver / person in charge *</label><input name="receiver_name" required/></div><label className="ptwDeclaration"><input type="checkbox" name="issuer_declaration" value="true" required/><span>I confirm the work area, documentation, hazards, isolations and precautions have been checked and the permit may be issued within its stated limits.</span></label><label className="ptwDeclaration"><input type="checkbox" name="receiver_declaration" value="true" required/><span>I accept control of the work, understand the precautions and will stop work if conditions change or the permit limits cannot be maintained.</span></label></div></section>
    <footer className="ptwSubmit"><div><strong>{readiness?"Ready to create controlled permit":"Permit checks incomplete"}</strong><span>{readiness?"The permit will be saved as a draft for final issue from its record page.":"Select at least one hazard and verify at least three precautions."}</span></div><button type="submit" disabled={!readiness}>Save draft permit</button></footer>
  </form>;
}
