"use client";
import {useState} from "react";
export default function RcaCaseControlFields({options,rcaCase,supplierId}) {
  const people=options.people || [],contacts=(options.contacts || []).filter(row=>row.supplier_id===supplierId),locations=options.locations || [];
  const personInitial=(key,nameKey)=>people.some(row=>row.id===rcaCase[key])?rcaCase[key]:people.find(row=>row.name===rcaCase[nameKey])?.id || (rcaCase[nameKey]?"legacy":"");
  const sourceInitial=rcaCase.stakeholder_supplier_contact_id && contacts.some(row=>row.id===rcaCase.stakeholder_supplier_contact_id)?"supplier_contact":rcaCase.stakeholder_person_id && people.some(row=>row.id===rcaCase.stakeholder_person_id)?"company_user":rcaCase.customer_or_stakeholder?"legacy":"";
  const [source,setSource]=useState(sourceInitial),[locationId,setLocationId]=useState(locations.find(row=>row.id===rcaCase.administration_location_id && row.label===rcaCase.location)?.id || locations.find(row=>row.label===rcaCase.location)?.id || (rcaCase.location?"legacy":""));
  const personField=(key,label,nameKey)=><label>{label}<select name={key} defaultValue={personInitial(key,nameKey)}><option value="">Select company user</option>{rcaCase[nameKey] && <option value="legacy">{rcaCase[nameKey]} — previously recorded</option>}{people.map(row=><option key={row.id} value={row.id}>{row.name}{row.email?` · ${row.email}`:""}</option>)}</select></label>;
  return <div className="rcaControlFields"><style>{`.rcaControlFields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:16px}.rcaControlFields label{display:grid;align-content:start;gap:7px;min-width:0;color:#173b60;font-size:14px;font-weight:800}.rcaControlFields :is(input,select){min-width:0;width:100%;min-height:48px;padding:12px 14px;border:1px solid #cfdae8;border-radius:10px;background:#fff;color:#061a35;font:16px Arial,sans-serif}.rcaControlFields .rcaControlWide{grid-column:1/-1}.rcaControlFields small{font-weight:400;line-height:1.5;color:#607089}.rcaControlFields :is(input,select):focus-visible{outline:3px solid #16a7b3;outline-offset:3px}@media(max-width:720px){.rcaControlFields{grid-template-columns:minmax(0,1fr)}}`}</style>
    {!people.length && <p className="rcaControlWide">No active company users. Add or activate users under <a href="/portal/company/people">Administration → People, Roles &amp; Access</a>.</p>}
    {personField("sponsor_person_id","Sponsor","sponsor_name")}{personField("leader_person_id","8D leader","leader_name")}
    <label>Customer / stakeholder source<select name="stakeholder_source" value={source} onChange={event=>setSource(event.target.value)}><option value="">Not assigned</option><option value="company_user">Company user</option>{supplierId && <option value="supplier_contact">Linked supplier contact</option>}{rcaCase.customer_or_stakeholder && <option value="legacy">Previously recorded stakeholder</option>}</select></label>
    {source==="company_user" && <label>Company stakeholder<select name="stakeholder_person_id" required defaultValue={rcaCase.stakeholder_person_id || ""}><option value="">Select company user</option>{people.map(row=><option key={row.id} value={row.id}>{row.name}{row.email?` · ${row.email}`:""}</option>)}</select></label>}
    {source==="supplier_contact" && <label>Supplier contact<select name="stakeholder_supplier_contact_id" required defaultValue={rcaCase.stakeholder_supplier_contact_id || ""}><option value="">Select active supplier contact</option>{contacts.map(row=><option key={row.id} value={row.id}>{row.name}{row.email?` · ${row.email}`:""}</option>)}</select>{!contacts.length && <small>Add an active contact for this supplier in <a href="/portal/suppliers">Supplier Assurance</a>.</small>}</label>}
    {source==="legacy" && <label>Recorded stakeholder<input value={rcaCase.customer_or_stakeholder || ""} readOnly/></label>}
    <label>Product / service / process<input name="product_service_process" defaultValue={rcaCase.product_service_process || ""}/></label>
    <label>Location — Administration<select name="administration_location_id" value={locationId} onChange={event=>setLocationId(event.target.value)}><option value="">Select business address</option>{rcaCase.location && <option value="legacy">{rcaCase.location} — previously recorded</option>}{locations.map(row=><option key={row.id} value={row.id}>{row.label}</option>)}</select><input type="hidden" name="administration_location_label" value={locations.find(row=>row.id===locationId)?.label || ""}/><small>From <a href="/portal/company/business-profile">Administration → Business Profile</a>.{!locations.length && " Add your registered or additional site addresses there."}</small></label>
    <label>Target closure date<input type="date" name="target_close_date" defaultValue={rcaCase.target_close_date || ""}/></label>
  </div>;
}
