"use client";
import {useState,useActionState,startTransition} from "react";
export default function RcaCaseCreateForm({action,organizations,companyOptions}) {
  const [state,formAction,pending]=useActionState(action,null);
  const [organizationId,setOrganizationId]=useState(""),[source,setSource]=useState("standalone"),[auditId,setAuditId]=useState(""),[supplierId,setSupplierId]=useState(""),[findingId,setFindingId]=useState("");
  const options=companyOptions.find(row=>row.organizationId===organizationId);
  const findings=(options?.findings || []).filter(row=>row.status!=="withdrawn" && (source==="audit"?row.audit_id===auditId:row.supplier_id===supplierId));
  const finding=findings.find(row=>row.id===findingId);
  const reset=()=>{setAuditId("");setSupplierId("");setFindingId("");};
  return <form className="capaForm" onSubmit={event=>{event.preventDefault();if(pending)return;const data=new FormData(event.currentTarget);startTransition(()=>formAction(data));}}>
    <style>{`.capaForm .rcaLinkField{display:grid;gap:7px;min-width:0;font-size:13px;font-weight:800}.capaForm .rcaLinkField :is(input,select,textarea){min-width:0;min-height:48px;font-size:16px}.rcaLinkNotice{grid-column:1/-1;padding:14px;border-radius:10px;background:#eaf8f3;color:#174b3c;overflow-wrap:anywhere;line-height:1.5}.rcaLinkError{background:#fff1ed;color:#a33221}.capaForm small{font-weight:400;line-height:1.5}`}</style>
    {state?.error && <div className="rcaLinkNotice rcaLinkError" role="alert">{state.error}</div>}
    <label className="rcaLinkField">Organisation<select name="organization_id" required value={organizationId} onChange={event=>{setOrganizationId(event.target.value);reset();}} className="capaField"><option value="">Select organisation</option>{organizations.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
    <label className="rcaLinkField">Corrective-action route<select name="case_type" defaultValue="capa" className="capaField"><option value="capa">CAPA — proportionate 4-stage workflow</option><option value="8d">8D — complex/high-risk investigation</option></select><small>Use CAPA for contained, lower-complexity nonconformities. Use 8D for major, recurring, systemic or high-risk problems.</small></label>
    <label className="rcaLinkField">Case source<select name="source_type" value={source} onChange={event=>{setSource(event.target.value);reset();}} className="capaField">{[["standalone","Standalone problem"],["audit","Audit"],["complaint","Complaint"],["incident","Incident"],["defect","Defect"],["supplier","Supplier issue"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <label className="rcaLinkField">Severity<select name="severity" defaultValue="medium" className="capaField">{["critical","high","medium","low"].map(value=><option key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</select></label>
    {source==="audit" && <label className="rcaLinkField">Audit *<select name="linked_audit_id" required value={auditId} onChange={event=>{setAuditId(event.target.value);setFindingId("");}} className="capaField"><option value="">Select audit</option>{(options?.audits || []).map(row=><option key={row.id} value={row.id}>{row.audit_reference} — {row.title}</option>)}</select><small>{!options?.audits.length ? "Select a company with a recorded audit." : "Select the audit, then its nonconformity."}</small></label>}
    {source==="supplier" && <label className="rcaLinkField">Supplier *<select name="supplier_id" required value={supplierId} onChange={event=>{setSupplierId(event.target.value);setFindingId("");}} className="capaField"><option value="">Select supplier</option>{(options?.suppliers || []).map(row=><option key={row.id} value={row.id}>{row.legal_name}</option>)}</select></label>}
    {["audit","supplier"].includes(source) && <label className="rcaLinkField">Nonconformity *<select name="linked_finding_id" value={findingId} onChange={event=>setFindingId(event.target.value)} required className="capaField"><option value="">Select NC</option>{findings.map(row=><option key={row.id} value={row.id}>{row.finding_reference} — {row.title}{row.linked_rca_case_id ? " · Existing 8D case" : ""}</option>)}</select>{(auditId || supplierId) && !findings.length && <small>No NCs recorded for this selection. <a href="/portal/internal-audits">Open audits</a> or <a href="/portal/internal-audit-actions">NC register</a>.</small>}</label>}
    {finding && <div className="rcaLinkNotice">{finding.finding_reference} · {finding.title}<br/>{finding.linked_rca_case_id ? "This NC already has a CAPA–8D case. Continue opens that case." : "The new case will be linked to this NC."}</div>}
    <label className="rcaLinkField capaWide">Problem title<input name="title" required placeholder="Short problem title" className="capaField" key={findingId || source} defaultValue={finding ? `${finding.finding_reference} · ${finding.title}` : ""}/></label>
    <label className="rcaLinkField capaWide">Known facts<textarea name="problem_statement" rows={4} className="capaField" key={findingId || source} defaultValue={finding?.failure_statement || ""} placeholder="State the known facts. D2 will develop and verify the full problem definition."/></label>
    <button className="capaSubmit" disabled={pending}>{pending ? "Saving…" : finding?.linked_rca_case_id ? "Open linked CAPA–8D case" : "Create CAPA–8D case"}</button>
  </form>;
}
