
"use client";

import { useMemo, useState } from "react";

const t = (name, label, example, help = "") => ({ name, label, example, help, type: "text" });
const a = (name, label, example, help = "") => ({ name, label, example, help, type: "area" });
const s = (name, label, options, example) => ({ name, label, options, example, type: "select" });
const m = (name, label, options, example) => ({ name, label, options, example, type: "multi" });

const riskScale = ["1 — Very unlikely", "2 — Unlikely", "3 — Possible", "4 — Likely", "5 — Very likely"];
const severityScale = ["1 — Insignificant", "2 — Minor", "3 — Moderate", "4 — Major", "5 — Catastrophic"];

const classifyExamples = {
  Physical: {
    hazard: "High noise generated by the bench grinder during prolonged use",
    exposure: "The operator and nearby employees are exposed throughout grinding and wheel run-up",
    harm: "Repeated exposure causes permanent noise-induced hearing loss or tinnitus",
    abnormal: "A longer-than-planned task, damaged wheel or missing acoustic enclosure increases the exposure.",
  },
  Mechanical: {
    hazard: "Rotating abrasive wheel operating at high speed",
    exposure: "Operator stands in the line of fire while testing with the guard open",
    harm: "Wheel fragments strike the operator, causing serious eye or facial injury",
    abnormal: "Incorrect wheel fitting, a damaged wheel or overspeed could cause failure during run-up.",
  },
  Chemical: {
    hazard: "Airborne metal dust and hazardous residue released during grinding",
    exposure: "The operator inhales dust and receives skin or eye contact while grinding and cleaning",
    harm: "Exposure causes respiratory irritation, occupational lung disease or serious eye injury",
    abnormal: "Extraction failure, dry sweeping or grinding a coated component significantly increases exposure.",
  },
  Biological: {
    hazard: "Contaminated residue on a component previously exposed to biological material",
    exposure: "The operator contacts contaminated dust through inhalation, broken skin or hand-to-mouth transfer",
    harm: "Exposure causes infection, allergic reaction or work-related illness",
    abnormal: "The component arrives without decontamination confirmation or contamination is discovered during grinding.",
  },
  Ergonomic: {
    hazard: "Sustained awkward posture and force while holding the workpiece at the grinder",
    exposure: "The operator repeatedly grips, lifts and controls the component with bent wrists and raised shoulders",
    harm: "Cumulative exposure causes upper-limb musculoskeletal injury or acute strain",
    abnormal: "An oversized component, extended production run or poorly adjusted workstation increases the load.",
  },
  Psychosocial: {
    hazard: "Production pressure and fatigue influencing the wheel-change and testing process",
    exposure: "The operator rushes the task, omits checks or continues while fatigued to recover lost production time",
    harm: "Impaired decisions contribute to serious injury and may also cause work-related stress or ill health",
    abnormal: "Breakdown recovery, understaffing or an urgent deadline increases pressure to bypass the safe method.",
  },
  Environmental: {
    hazard: "Metal dust, used abrasive material and contaminated waste released from grinding",
    exposure: "Waste enters general refuse, drains or the surrounding environment during use and cleaning",
    harm: "The release contaminates land or water and exposes others handling uncontrolled waste",
    abnormal: "Extraction collection fails, a spill occurs or hazardous coatings are present on the workpiece.",
  },
};

const exercises = {
  classify: [
    s("category", "Hazard category", ["Physical", "Mechanical", "Chemical", "Biological", "Ergonomic", "Psychosocial", "Environmental"], "Mechanical"),
    t("hazard", "Hazard source", "Rotating abrasive wheel operating at high speed", "Name the source of harm, not the injury."),
    t("exposure", "Exposure route", "Operator stands in the line of fire while testing with the guard open", "Describe exactly how a person encounters it."),
    t("harm", "Credible consequence", "Wheel fragments strike the operator, causing serious eye or facial injury"),
    a("abnormal", "Abnormal condition", "Incorrect wheel fitting, a damaged wheel or overspeed could cause failure during run-up."),
  ],
  people_map: [
    m("people", "People who may be affected", ["Operator", "Contractor", "Maintenance staff", "Nearby employees", "Delivery driver", "Visitor or public", "New starter", "Lone worker"], ["Operator", "Contractor", "Nearby employees", "Delivery driver"]),
    a("map", "People-at-risk map", "Operator — unexpected plant movement or released oil — crushing injury, burns or a slip. Contractor — stored pressure and oil release — injection injury. Nearby employees — unexpected plant movement — crushing injury. Delivery driver — vehicle enters the work area — collision.", "Link every selected group to an exposure and credible harm."),
    t("consult", "People to consult", "Contractor, operators, area supervisor, maintenance lead and logistics coordinator"),
  ],
  matrix: [
    s("likelihood", "Initial likelihood", riskScale, "4 — Likely"),
    s("severity", "Credible severity", severityScale, "5 — Catastrophic"),
    t("score", "Risk score", "20", "Multiply likelihood by severity."),
    s("decision", "Can the work proceed?", ["Yes — controls are adequate", "Yes — with additional controlled action", "No — stop until risk is reduced"], "No — stop until risk is reduced"),
    a("rationale", "Evidence-based rationale", "Recent monitor pump failures and overdue portable-detector calibration make exposure foreseeable. A fatal low-oxygen atmosphere is credible. Entry must stop until detection, calibration and rescue arrangements are verified."),
  ],
  rank_controls: [
    m("levels", "Hierarchy levels considered", ["Eliminate", "Substitute", "Engineering", "Administrative", "PPE"], ["Eliminate", "Engineering", "Administrative", "PPE"]),
    a("controls", "Controls in hierarchy order", "1. Eliminate enclosed-bay welding where practicable. 2. Install source LEV. 3. Restrict access and verify airflow. 4. Use fit-tested RPE for residual exposure."),
    t("strongest", "Strongest selected control", "Effective source extraction verified by commissioning and examination"),
    t("verification", "Effectiveness evidence", "LEV capture test, statutory thorough examination and exposure monitoring where necessary"),
  ],
  record_quality: [
    t("activity", "Defined activity", "Routine adjustment and cleaning of the guarded conveyor drive in Production Cell 2"),
    a("risk", "Hazard, exposure and harm", "Unexpected energisation during adjustment could draw the technician into the drive, causing crushing or amputation."),
    a("controls", "Existing and further controls", "Existing: fixed guard and local stop. Further: lockable isolation, prove-dead step and controlled access before guard removal."),
    t("owner", "Action owner and date", "Engineering Manager — before the next planned intervention"),
    t("evidence", "Completion evidence", "Approved isolation instruction, installed isolator and witnessed functional test"),
  ],
  review_decision: [
    m("triggers", "Review triggers", ["Control failure", "Worker concern", "Monitoring result", "Inspection defect", "Incident or near miss", "Process change"], ["Control failure", "Worker concern", "Inspection defect"]),
    a("precautions", "Immediate precautions", "Restrict the fume-producing task and provide alternative extraction until airflow is restored and verified."),
    a("scope", "Assessment review scope", "Review the process, materials, exposure duration, affected people, LEV performance, RPE and maintenance arrangements."),
    t("evidence", "Evidence before acceptance", "Repair record, satisfactory airflow test, current examination and worker confirmation"),
  ],
  assessment_plan: [
    t("scope", "Task and boundaries", "Hydraulic-hose replacement inside the guarded production cell, including isolation, oil containment and shift handover"),
    a("risk", "Highest-priority risk", "Shared energy and residual pressure could move equipment while people are inside, causing fatal crushing or injection injury."),
    s("decision", "Work decision", ["Proceed under existing controls", "Proceed only after additional controls", "Stop until risk is reduced"], "Stop until risk is reduced"),
    a("controls", "Control package", "Shut down; isolate and lock shared energy; discharge and prove zero pressure; control access; contain oil; brief the team and control shift handover."),
    t("owner", "Action owner", "Production Engineering Manager"),
    t("evidence", "Verification evidence", "Signed isolation and try-out record, zero-pressure verification, permit and briefing record"),
    t("review", "Review trigger", "Any isolation failure, task change, near miss or incomplete handover"),
  ],
  rapid_review: [
    t("assessment", "Assessment selected", "Workshop bench-grinder risk assessment"),
    m("reasons", "Reasons for review", ["Equipment changed", "Control deteriorated", "Worker concern", "Incident or near miss", "New guidance", "Exposure changed", "Record differs from practice"], ["Control deteriorated", "Record differs from practice"]),
    a("first_check", "First practical check", "Compare the recorded guarding and wheel-change method with the machine and observe a competent operator completing the task."),
  ],
  hazard_refresh: [
    t("hazard", "Hazard source", "Forklift movement through a shared doorway with restricted visibility"),
    t("exposure", "Exposure route", "Pedestrians and drivers enter the same blind doorway while stock obstructs the mirror"),
    m("people", "People at risk", ["Forklift drivers", "Employees", "Contractors", "Visitors", "Delivery drivers", "Public"], ["Forklift drivers", "Employees", "Contractors", "Visitors"]),
    t("harm", "Credible harm", "A pedestrian is struck or trapped, causing major crush injury or fatality"),
    a("action", "Immediate action", "Stop shared use, remove the obstruction and introduce temporary physical segregation until permanent controls are restored."),
  ],
  calibration: [
    t("assessment", "Assessment selected", "Monthly entry into the low-oxygen pit"),
    s("likelihood", "Likelihood", riskScale, "4 — Likely"),
    s("severity", "Severity", severityScale, "5 — Catastrophic"),
    a("evidence", "Evidence for both inputs", "Entry is monthly, but monitor failures and overdue calibration reduce confidence. Unrecognised oxygen deficiency could cause fatality."),
    s("match", "Does the action match the band?", ["Yes", "No", "Not enough evidence"], "No"),
    a("correction", "Required correction", "Stop entry until detection, calibration, ventilation and rescue arrangements are verified."),
  ],
  control_refresh: [
    t("package", "Control package reviewed", "Welding-fume controls in the enclosed fabrication bay"),
    s("level", "Strongest control level", ["Elimination", "Substitution", "Engineering", "Administrative", "PPE"], "Engineering"),
    t("strongest", "Strongest control", "Source LEV positioned at the weld"),
    t("weakness", "Weakest dependency", "Operator positioning the hood correctly for every weld"),
    t("verification", "Verification check", "Airflow check before use plus current thorough-examination record"),
  ],
  template_review: [
    m("gaps", "Record gaps", ["Activity scope", "Hazard and harm", "People at risk", "Control evidence", "Rating rationale", "Further action", "Owner and date", "Residual rating", "Implementation evidence", "Approval or review"], ["Hazard and harm", "Rating rationale", "Implementation evidence"]),
    s("first", "First field to correct", ["Activity scope", "Hazard and harm", "People at risk", "Existing controls", "Rating rationale", "Further action", "Owner and date", "Implementation evidence"], "Hazard and harm"),
    a("original", "Current entry", "Hazard: machinery. Harm: injury. Control: trained staff."),
    a("improved", "Improved entry", "During unguarded conveyor adjustment, unexpected energisation could draw the technician into the drive and cause crushing or amputation. Lockable isolation is required before guard removal."),
  ],
  final_refresh: [
    s("decision", "May temporary operation proceed?", ["Yes — as proposed", "Yes — only after additional controls", "No — operation must remain stopped"], "No — operation must remain stopped"),
    m("reasons", "Why the assessment may be invalid", ["Operating mode changed", "Interlock unavailable", "Exposure changed", "Competence changed", "Controls weakened", "Temporary arrangement not assessed"], ["Operating mode changed", "Interlock unavailable", "Controls weakened", "Temporary arrangement not assessed"]),
    a("controls", "Controls required", "Repair and test the interlock or establish an engineered alternative; isolate for intervention; restrict access and authorise competent operators."),
    a("approval", "Approval and verification", "Engineering and operations management approval after functional testing, risk review, briefing and recorded pre-use verification."),
    a("rationale", "Decision rationale", "PPE and an instruction do not replace the failed engineered safeguard or prevent access to dangerous movement."),
  ],
};

function schemaFor(type) {
  return exercises[type] || [a("response", "Your practical response", "Identify the issue, record your decision, assign an owner and define verification evidence.")];
}

function exampleFor(field, interactionType, answers) {
  if (interactionType !== "classify" || field.name === "category") return field.example;
  const category = answers.category || "Mechanical";
  return classifyExamples[category]?.[field.name] || field.example;
}

const fieldPurpose = {
  hazard: "A clear source of harm is needed before suitable controls can be chosen.",
  exposure: "The assessment must explain how contact or exposure can actually occur.",
  harm: "A specific credible outcome is needed to support a defensible severity judgement.",
  abnormal: "Non-routine and foreseeable failure conditions are part of a suitable assessment.",
  people: "Every affected group may need different controls, information or supervision.",
  map: "Each selected group must be linked to a specific exposure and credible harm.",
  consult: "The people doing, controlling and affected by the work hold evidence needed for the decision.",
  likelihood: "Likelihood must reflect exposure frequency and the reliability of current controls.",
  severity: "Severity must use the worst credible outcome, without exaggeration or understatement.",
  score: "The score must match the selected likelihood and severity values.",
  decision: "The work decision must match the risk level and current control reliability.",
  rationale: "The rationale provides auditable evidence for the learner's judgement.",
  controls: "Controls should address the source and clearly define what must change.",
  evidence: "Objective evidence is required before an action or control can be accepted as complete.",
  owner: "An action without clear ownership is unlikely to be controlled to completion.",
  review: "A defined trigger keeps the assessment aligned with changes and new evidence.",
};

function coachingReview(fields, answers, interactionType) {
  const prompts = [];

  fields.forEach((field) => {
    const value = answers[field.name];
    const missing = field.type === "multi" ? !Array.isArray(value) || value.length === 0 : !String(value || "").trim();
    if (missing) prompts.push({ title: `Complete “${field.label}”`, explanation: fieldPurpose[field.name] || "This evidence is required to demonstrate that the scenario has been considered." });
  });

  if (interactionType === "people_map") {
    const selected = answers.people || [];
    const required = {
      Operator: "Operators are working nearby and could be exposed to unexpected movement, released oil or loss of access.",
      Contractor: "The contractor performs the intervention and may not be able to see the isolation point.",
      "Nearby employees": "The scenario confirms that other people remain in the production area during the work.",
      "Delivery driver": "The delivery route crosses the work area, creating a separate vehicle and access exposure.",
    };
    Object.entries(required).forEach(([person, explanation]) => {
      if (!selected.includes(person)) prompts.push({ title: `Consider adding: ${person}`, explanation });
    });

    const map = String(answers.map || "").toLowerCase();
    const keywords = { Operator: "operator", Contractor: "contractor", "Maintenance staff": "maintenance", "Nearby employees": "employee", "Delivery driver": "delivery", "Visitor or public": "visitor", "New starter": "starter", "Lone worker": "lone" };
    selected.forEach((person) => {
      if (map && !map.includes(keywords[person])) prompts.push({ title: `Link ${person} to exposure and harm`, explanation: "The group is selected, but the people-at-risk map does not yet show how that group could be harmed." });
    });
  }

  if (interactionType === "matrix") {
    const likelihood = Number.parseInt(answers.likelihood, 10);
    const severity = Number.parseInt(answers.severity, 10);
    const enteredScore = Number.parseInt(answers.score, 10);
    if (likelihood && severity && enteredScore !== likelihood * severity) prompts.push({ title: `Recalculate the risk score: ${likelihood} × ${severity} = ${likelihood * severity}`, explanation: "The recorded score must mathematically match the selected likelihood and severity." });
    if (enteredScore >= 15 && answers.decision && !answers.decision.startsWith("No")) prompts.push({ title: "Reconsider whether work can proceed", explanation: "A score of 15–25 is unacceptable in this model; work must stop until the risk is reduced." });
    if (enteredScore >= 10 && enteredScore <= 14 && answers.decision?.startsWith("Yes — controls are adequate")) prompts.push({ title: "Further controlled action is required", explanation: "A score of 10–14 is inadequate and cannot be accepted as requiring no further action." });
  }

  if (["rapid_review", "review_decision", "template_review", "final_refresh"].includes(interactionType)) {
    const multiField = fields.find((field) => field.type === "multi");
    if (multiField && Array.isArray(answers[multiField.name]) && answers[multiField.name].length < 2) prompts.push({ title: `Select another relevant ${multiField.label.toLowerCase()}`, explanation: "This scenario contains more than one indicator; recognising interacting factors produces a more suitable review." });
  }

  return { passed: prompts.length === 0, prompts };
}

export default function StructuredPracticalExercise({ module, enrolment, completeModuleAction, onBack }) {
  const content = module.content || {};
  const interaction = content.interaction || { type: "reflection", instruction: content.reflection || "Apply this module to a practical example." };
  const fields = useMemo(() => schemaFor(interaction.type), [interaction.type]);
  const blank = () => Object.fromEntries(fields.map((field) => [field.name, field.type === "multi" ? [] : ""]));
  const [answers, setAnswers] = useState(blank);
  const [answerModes, setAnswerModes] = useState({});
  const [usedExample, setUsedExample] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [coaching, setCoaching] = useState(null);

  function loadExample(checked) {
    setUsedExample(checked);
    setConfirmed(false);
    setCoaching(null);
    setAnswers((current) => {
      if (!checked) return blank();
      const category = interaction.type === "classify" ? current.category || "Mechanical" : current.category;
      const basis = { ...current, category };
      return Object.fromEntries(fields.map((field) => [field.name, exampleFor(field, interaction.type, basis)]));
    });
    setAnswerModes(checked ? Object.fromEntries(fields.map((field) => [field.name, "suggested"])) : {});
  }

  function updateMulti(name, option, checked) {
    setAnswers((current) => ({ ...current, [name]: checked ? [...current[name], option] : current[name].filter((item) => item !== option) }));
    setCoaching(null);
    setConfirmed(false);
  }

  function chooseAnswerMode(field, mode) {
    setAnswerModes((current) => ({ ...current, [field.name]: mode }));
    setAnswers((current) => ({ ...current, [field.name]: mode === "own" ? "" : exampleFor(field, interaction.type, current) }));
    setConfirmed(false);
    setCoaching(null);
  }

  function updateSelect(field, value) {
    setAnswers((current) => {
      const next = { ...current, [field.name]: value };
      if (interaction.type === "classify" && field.name === "category") {
        fields.forEach((dependent) => {
          if (dependent.name !== "category" && answerModes[dependent.name] === "suggested") {
            next[dependent.name] = exampleFor(dependent, interaction.type, next);
          }
        });
      }
      return next;
    });
    setConfirmed(false);
    setCoaching(null);
  }

  function checkResponse() {
    setConfirmed(false);
    setCoaching(coachingReview(fields, answers, interaction.type));
  }

  const evidence = JSON.stringify({ version: 3, interaction_type: interaction.type, used_worked_example: usedExample, response_modes: answerModes, coaching_check_passed: Boolean(coaching?.passed), learner_confirmed: confirmed, answers });

  return <div className="spePage">
    <style>{`
      .spePage{color:#092748}.speBack{padding:0;border:0;background:none;color:#245cff;font-weight:850;cursor:pointer}.speHead{margin:22px 0;padding:25px;border-radius:15px;background:linear-gradient(135deg,#082a54,#087f6c);color:#fff}.speHead small{font-weight:900;letter-spacing:.11em;color:#78e3c4}.speHead h2{margin:8px 0;font-size:31px}.speHead p{margin:0;line-height:1.55}.speScenario{margin:16px 0;padding:18px;border:1px solid #c9dcfa;border-radius:12px;background:#edf4ff}.speScenario small{font-weight:900;color:#245cff;letter-spacing:.08em}.speScenario h3{margin:6px 0}.speScenario p{margin:0;color:#496681;line-height:1.5}.speExample,.speConfirm{display:flex;gap:12px;align-items:flex-start;margin:16px 0;padding:16px;border:1px solid #c7d7e5;border-radius:11px;background:#f4f8fc;cursor:pointer}.speExample input,.speConfirm input{width:19px;height:19px;margin-top:2px;accent-color:#087f6c}.speExample span{display:grid;gap:3px}.speExample small{color:#5f768c}.speGrid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.speField{min-width:0;margin:0;padding:16px;border:1px solid #d6e1ea;border-radius:11px}.speField.wide{grid-column:1/-1}.speField legend{padding:0 7px;font-weight:900}.speField legend i{display:inline-grid;place-items:center;width:27px;height:27px;margin-right:8px;border-radius:50%;background:#e8f0ff;color:#245cff;font-size:10px;font-style:normal}.speHelp{margin:2px 0 11px;color:#60778e;font-size:13px}.speField input:not([type=checkbox]),.speField select,.speField textarea{box-sizing:border-box;width:100%;padding:11px;border:1px solid #aebfd0;border-radius:8px;background:#fff;font:inherit}.speField textarea{min-height:105px;resize:vertical}.speOptions{position:relative;display:flex;flex-wrap:wrap;gap:7px}.speOptions label{cursor:pointer}.speOptions label input{position:absolute;opacity:0}.speOptions label span{display:block;padding:9px 10px;border:1px solid #c8d8e5;border-radius:999px;color:#34536f;font-size:12px;font-weight:800}.speOptions label input:checked+span{border-color:#087f6c;background:#e4f7f1;color:#05634f}.speValidator{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;opacity:0;pointer-events:none}.speConfirm{background:#fff8e6;border-color:#e9c568}.speSubmit{width:100%;padding:13px 16px;border:0;border-radius:9px;background:#087f6c;color:#fff;font-weight:900;font-size:15px;cursor:pointer}.speNote{text-align:center;color:#687d91;font-size:12px}@media(max-width:650px){.speGrid{grid-template-columns:1fr}.speField.wide{grid-column:auto}.speHead h2{font-size:25px}}
    `}</style>
    <style>{`.speAnswerModes{display:grid;gap:6px;margin:0 0 11px}.speAnswerModes label{display:flex;gap:8px;align-items:center;padding:8px 10px;border:1px solid #d8e3ec;border-radius:8px;background:#f7fafc;cursor:pointer;font-size:12px;font-weight:750}.speAnswerModes label:has(input:checked){border-color:#3573ee;background:#edf3ff;color:#174cae}.speAnswerModes input{width:auto!important;accent-color:#245cff}.speCoachButton{width:100%;margin-top:17px;padding:12px;border:2px solid #245cff;border-radius:9px;background:#fff;color:#174cae;font-weight:900;cursor:pointer}.speCoach{margin:14px 0;padding:17px;border-radius:12px}.speCoach.pass{border:1px solid #8fd7bd;background:#eaf8f2}.speCoach.prompt{border:1px solid #efc66a;background:#fff8e6}.speCoach h3{margin:0 0 8px}.speCoach p{margin:4px 0}.speCoach ul{display:grid;gap:9px;margin:10px 0 0;padding-left:20px}.speCoach li strong{display:block}.speCoach li span{display:block;margin-top:2px;color:#5c6f7d}.speConfirm.disabled{opacity:.55;cursor:not-allowed}.speSubmit:disabled{background:#91a5b5;cursor:not-allowed}`}</style>
    <button type="button" className="speBack" onClick={onBack}>← Return to learning</button>
    <header className="speHead"><small>PRACTICAL EXERCISE</small><h2>Demonstrate your decision</h2><p>{interaction.instruction}</p></header>
    {content.scenario && <section className="speScenario"><small>SCENARIO REFERENCE</small><h3>{content.scenario.title}</h3><p>{content.scenario.context || content.scenario.prompt}</p></section>}
    <label className="speExample"><input type="checkbox" checked={usedExample} onChange={(event) => loadExample(event.target.checked)}/><span><strong>Use a worked example</strong><small>Populate a model response. You must review it and can modify any answer before submission.</small></span></label>
    <div className="speGrid" onChange={() => { setCoaching(null); setConfirmed(false); }}>{fields.map((field, index) => <fieldset className={`speField ${field.type === "area" ? "wide" : ""}`} key={field.name}><legend><i>{String(index + 1).padStart(2, "0")}</i>{field.label}</legend>{field.help && <p className="speHelp">{field.help}</p>}
      {(field.type === "text" || field.type === "area") && <div className="speAnswerModes" role="radiogroup" aria-label={`${field.label} response method`}>
        <label><input type="radio" name={`mode-${field.name}`} checked={answerModes[field.name] === "suggested"} onChange={() => chooseAnswerMode(field, "suggested")}/>Select the suggested response</label>
        <label><input type="radio" name={`mode-${field.name}`} checked={answerModes[field.name] === "own"} onChange={() => chooseAnswerMode(field, "own")}/>Add my own response</label>
        <label><input type="radio" name={`mode-${field.name}`} checked={answerModes[field.name] === "modify"} onChange={() => chooseAnswerMode(field, "modify")}/>Start with the example and modify it</label>
      </div>}
      {field.type === "select" && <select required value={answers[field.name]} onChange={(event) => updateSelect(field, event.target.value)}><option value="">Select an answer</option>{field.options.map((option) => <option key={option}>{option}</option>)}</select>}
      {field.type === "text" && <input required minLength={3} value={answers[field.name]} onChange={(event) => setAnswers({ ...answers, [field.name]: event.target.value })}/>} 
      {field.type === "area" && <textarea required minLength={20} value={answers[field.name]} onChange={(event) => setAnswers({ ...answers, [field.name]: event.target.value })}/>} 
      {field.type === "multi" && <div className="speOptions">{field.options.map((option) => <label key={option}><input type="checkbox" checked={answers[field.name].includes(option)} onChange={(event) => updateMulti(field.name, option, event.target.checked)}/><span>{option}</span></label>)}<input className="speValidator" tabIndex={-1} aria-hidden="true" required value={answers[field.name].length ? "selected" : ""} onChange={() => {}}/></div>}
    </fieldset>)}</div>
    <button className="speCoachButton" type="button" onClick={checkResponse}>Check my response and show guidance</button>
    {coaching && <section className={`speCoach ${coaching.passed ? "pass" : "prompt"}`} aria-live="polite">{coaching.passed ? <><h3>✓ Response check complete</h3><p>No required scenario element is missing. Review your reasoning, then confirm your response below.</p></> : <><h3>Review these points before continuing</h3><p>The engine found {coaching.prompts.length} point{coaching.prompts.length === 1 ? "" : "s"} requiring attention:</p><ul>{coaching.prompts.map((prompt, index) => <li key={`${prompt.title}-${index}`}><strong>{prompt.title}</strong><span>{prompt.explanation}</span></li>)}</ul></>}</section>}
    <label className={`speConfirm ${coaching?.passed ? "" : "disabled"}`}><input type="checkbox" required disabled={!coaching?.passed} checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/><span><strong>I have reviewed this response.</strong> It reflects my decision for the scenario, and I can explain the selected controls and evidence.</span></label>
    <form action={completeModuleAction}><input type="hidden" name="enrolment_id" value={enrolment.id}/><input type="hidden" name="module_id" value={module.id}/><input type="hidden" name="learner_reflection" value={evidence}/><button className="speSubmit" type="submit" disabled={!coaching?.passed || !confirmed}>Submit exercise and complete module →</button></form>
    <p className="speNote">The structured response, worked-example status and learner confirmation are retained as module evidence.</p>
  </div>;
}
