import { siteEmergencyContacts, emergencyContactFor } from "./bcpIncidentEmergencyContacts";
export const planList = (v) => Array.isArray(v) ? v : [];
const t = (v) => String(v ?? "").trim();
const lines = (values) => values.filter((v) => t(v)).join("\n");
export const PLAN_SOURCE_TABLES = { site: "bcp_site_profiles", incident: "bcp_incident_management_assessments", bia: "bcp_bia_assessments", strategy: "bcp_strategy_assessments", hazards: "bcp_hazard_assessments", roles: "bcp_role_assessments", context: "bcp_context_assessments", outsourced: "bcp_outsourced_process_assessments" };
export const PLAN_SOURCE_LABELS = { site: "Module 1 · Site Profile", context: "Module 3 · Context", roles: "Module 4 · Roles", hazards: "Module 5 · Hazards", bia: "Module 6 · BIA", outsourced: "Module 7 · Outsourced processes", strategy: "Module 8 · Strategies", incident: "Module 9 · Incident management" };
export const PREPARATION_OPTIONS = ["Confirm alternate workplace and access arrangements", "Check availability of required people and skills", "Verify controlled backups and recovery access", "Confirm supplier and external support arrangements", "Check required equipment, connectivity and utilities", "Brief response teams and deputies on their tasks"];
export const PROTECTION_OPTIONS = ["Follow approved emergency arrangements to protect people", "Confirm safe access before moving people or restarting activities", "Control environmental releases and further damage", "Protect essential records, data and priority equipment", "Escalate unresolved safety or environmental restrictions"];
export const REPORTING_OPTIONS = ["Record activation decisions, time and authorising person", "Maintain the incident timeline and decision log", "Report process capacity and progress against recovery targets", "Record unresolved issues, owners and escalation decisions", "Issue updates to affected parties through approved channels", "Record handback, stand-down and follow-up actions"];
export const PROCEDURE_STEPS = [
  ["assess", "Assess the disruption", "Confirm the impact on this activity, available staff, dependencies and restrictions. Report the findings to incident coordination."],
  ["people", "Confirm people and deputies", "Contact the assigned people and deputies. Confirm availability and the required skills before allocating tasks."],
  ["resources", "Mobilise required resources", "Confirm the listed resources, access, equipment, information and external support. Escalate shortages affecting the recovery target."],
  ["location", "Verify the recovery location", "Confirm the recorded execution location is usable and any required access, safety and connectivity checks are complete."],
  ["implement", "Implement the selected solution", "Implement the operational solution recorded below using the local instructions. Record decisions and any deviation from the agreed arrangements."],
  ["capacity", "Verify minimum operating capacity", "Check actual service capacity against the BIA minimum capacity and recovery time objective; report any shortfall immediately."],
  ["monitor", "Monitor and report progress", "Use the reporting schedule to record achieved capacity, remaining risks and recovery progress."],
  ["restore", "Restore and hand back operations", "Verify full recovery against the recorded target and Module 9 handback conditions. Obtain authorised handback and record the transition."],
];
export function normalisePlanData(raw = {}) {
  const result = {};
  for (const field of ["title", "purpose", "scope", "planOwnerPersonId", "deputyPersonId", "approverPersonId", "activationNotes", "preparationNotes", "protectionNotes", "dependenciesNotes", "incomingCommunications", "mediaArrangements", "reportingFrequency", "reportingNotes", "recoveryNotes", "planLocation", "reviewFrequency", "nextReviewDate", "maintenanceNotes", "reviewComment"]) result[field] = t(raw[field]).slice(0, 8000);
  for (const [field, options] of [["preparationSelections", PREPARATION_OPTIONS], ["protectionSelections", PROTECTION_OPTIONS], ["reportingSelections", REPORTING_OPTIONS]]) result[field] = [...new Set(planList(raw[field]).filter((v) => options.includes(v)))];
  result.participantIds = [...new Set(planList(raw.participantIds).map((v) => t(v).slice(0,80)))].slice(0,200);
  result.activityIds = Array.isArray(raw.activityIds) ? [...new Set(raw.activityIds.map((v) => t(v).slice(0,100)))].slice(0,500) : null;
  result.activityPlans = Object.fromEntries(Object.entries(raw.activityPlans && typeof raw.activityPlans === "object" && !Array.isArray(raw.activityPlans) ? raw.activityPlans : {}).slice(0,500).map(([key, row]) => [key.slice(0,200), { location: t(row?.location).slice(0,8000), instructions: t(row?.instructions).slice(0,16000), ownerPersonId: t(row?.ownerPersonId).slice(0,80), deputyPersonId: t(row?.deputyPersonId).slice(0,80), stepIds: Array.isArray(row?.stepIds) ? [...new Set(row.stepIds.filter((id) => PROCEDURE_STEPS.some(([key]) => key === id)))] : PROCEDURE_STEPS.map(([id]) => id) }]));
  result.additionalContacts = planList(raw.additionalContacts).slice(0,100).map((r) => Object.fromEntries(["name", "role", "organisation", "contact"].map((key) => [key, t(r?.[key]).slice(0,500)])));
  return result;
}
export function planPerson(id, people, fallback = "Not assigned") { const p = planList(people).find((row) => row.id === id); return p ? [p.first_name, p.last_name].filter(Boolean).join(" ") : fallback; }
export function evaluatedPlanHazards(hazard, siteId) {
  if (!siteId || hazard?.site_profile_id !== siteId) return [];
  return planList(hazard.scenario_assessments).filter((r) => r.id && t(r.name) && r.includeInIncidentPlan !== false && t(r.description) && planList(r.affectedProcesses).length && planList(r.applicableSystems).length && planList(r.existingControls).length && t(r.owner) && t(r.treatment) && t(r.decisionRationale) && Number(r.likelihood) >= 1 && Number(r.likelihood) <= 5 && Number(r.controlEffectiveness) >= 0 && Number(r.controlEffectiveness) <= 100 && Object.values(r.impact || {}).length > 0 && Object.values(r.impact || {}).every((v) => Number(v) >= 0 && Number(v) <= 5) && Object.values(r.impact || {}).some((v) => Number(v) > 0) && (Math.max(...Object.values(r.impact || {}).map(Number),1) * Math.max(1,Math.ceil(Number(r.likelihood)*(1-Number(r.controlEffectiveness)/100))) < 6 || planList(r.actions).length > 0));
}
export function planActivities(bia) { return planList(bia?.activity_assessments).filter((a) => a.id && a.included !== false); }
export function planSourceIssues(sources) {
  const issues = [];
  for (const key of ["site", "incident", "bia", "strategy", "hazards", "roles"]) if (!sources[key]) issues.push(`Select ${PLAN_SOURCE_LABELS[key]}`);
  const siteId = sources.site?.id;
  for (const key of ["incident", "bia", "hazards", "roles", "context"]) if (sources[key] && (!siteId || sources[key].site_profile_id !== siteId)) issues.push(`${PLAN_SOURCE_LABELS[key]} must belong to the selected Site Profile`);
  const incident = sources.incident;
  for (const [key, field] of [["hazards", "hazard_assessment_id"], ["roles", "role_assessment_id"], ["strategy", "strategy_assessment_id"], ["context", "context_assessment_id"]]) if (incident?.[field] && sources[key]?.id !== incident[field]) issues.push(`${PLAN_SOURCE_LABELS[key]} does not match the Module 9 source`);
  if (incident?.bia_assessment_id && sources.bia?.id !== incident.bia_assessment_id) issues.push("BIA must match the source linked in Module 9");
  if (sources.strategy && sources.strategy.bia_assessment_id !== sources.bia?.id) issues.push("Module 8 strategy must use the selected BIA");
  for (const key of ["bia", "strategy"]) if (sources[key]?.hazard_assessment_id && sources[key].hazard_assessment_id !== sources.hazards?.id) issues.push(`${PLAN_SOURCE_LABELS[key]} uses a different Hazard assessment`);
  if (sources.strategy?.outsourced_assessment_id && sources.outsourced?.id !== sources.strategy.outsourced_assessment_id) issues.push("Outsourced source must match Module 8");
  if (sources.outsourced) { const siteIds = planList(sources.outsourced.source_links?.siteProfiles); if (!(siteIds.includes(siteId) || sources.outsourced.site_profile_id === siteId)) issues.push("Module 7 outsourced source must include the selected site"); }
  return issues;
}
export function planSourceVersions(sources) { return Object.fromEntries(Object.entries(sources).filter(([, row]) => row).map(([key, row]) => [key, { id: row.id, version: row.version || 1, updatedAt: row.updated_at || "", status: row.status, reference: row.assessment_reference || row.profile_reference || "" }])); }
export function planSourceDrift(saved, current) { return Object.entries(saved || {}).filter(([key, value]) => !current[key] || current[key].id !== value.id || Number(current[key].version || 1) !== Number(value.version || 1) || (value.updatedAt && current[key].updated_at !== value.updatedAt)).map(([key]) => PLAN_SOURCE_LABELS[key] || key); }
export function planActivityRows(data, sources) {
  const source = planActivities(sources.bia);
  const ids = Array.isArray(data.activityIds) ? data.activityIds : source.map((a) => a.id);
  return source.filter((a) => ids.includes(a.id)).map((activity) => {
    const key = `${sources.bia.id}:${activity.id}`;
    const local = data.activityPlans?.[key] || {};
    const solution = planList(sources.strategy?.strategy_assessments).find((s) => (s.sourceId || s.id) === activity.id);
    return { activity, solution, key, local: { ...local, stepIds: Array.isArray(local.stepIds) ? local.stepIds : PROCEDURE_STEPS.map(([id]) => id), ownerPersonId: local.ownerPersonId || activity.ownerPersonId || "", deputyPersonId: local.deputyPersonId || data.deputyPersonId || "" } };
  });
}
const objective = (a, key) => a[key] ?? a.calculated?.[key];
export function planMissing(data, sources, people) {
  const missing = planSourceIssues(sources).map((label) => ({ step: 0, label }));
  for (const [field, label] of [["title", "Enter a plan title"], ["scope", "Define the plan scope"], ["planOwnerPersonId", "Select the plan owner"], ["deputyPersonId", "Select the plan deputy"]]) if (!t(data[field])) missing.push({ step: 0, label });
  if (data.planOwnerPersonId && data.planOwnerPersonId === data.deputyPersonId) missing.push({ step: 0, label: "Choose a different plan deputy" });
  const personIds = [data.planOwnerPersonId, data.deputyPersonId, data.approverPersonId, ...planList(data.participantIds)];
  const rows = planActivityRows(data, sources);
  for (const [parent, mapping] of [["incident", {site:"site",hazards:"hazards",roles:"roles",context:"context",bia:"bia",strategy:"strategy"}], ["strategy",{bia:"bia",hazard:"hazards",outsourced:"outsourced"}], ["bia",{siteProfile:"site",context:"context",roles:"roles",hazards:"hazards"}]]) {
    for (const [metaKey,key] of Object.entries(mapping)) {
      const meta = sources[parent]?.source_versions?.[metaKey], snapshot = sources[parent]?.source_snapshot?.[key] || sources[parent]?.source_snapshot?.[({site:"profile",hazards:"hazard",roles:"role"})[key]];
      if (!sources[key] || meta == null) continue;
      const linkedVersion = typeof meta === "object" ? meta.version : meta;
      if (Number(linkedVersion || 1) !== Number(sources[key].version || 1) || (typeof meta === "object" && meta.id && meta.id !== sources[key].id) || (snapshot?.updated_at && snapshot.updated_at !== sources[key].updated_at)) missing.push({step:0,label:`Refresh and reapprove ${PLAN_SOURCE_LABELS[parent]} after changes to ${PLAN_SOURCE_LABELS[key]}`});
    }
  }
  if (!rows.length) missing.push({ step: 1, label: "Select at least one BIA activity" });
  const availableIds = new Set(planActivities(sources.bia).map((a) => a.id));
  for (const id of planList(data.activityIds)) if (!availableIds.has(id)) missing.push({ step: 1, label: "A selected BIA activity is no longer available; confirm the activity selection" });
  for (const { activity: a, solution: s, local } of rows) {
    const rto = Number(objective(a, "rtoHours")), mtpd = Number(objective(a, "mtpdHours") || a.calculated?.detectedMtpdHours), mbco = Number(a.mbcoPercent);
    if (!(rto > 0 && mtpd > rto && mbco > 0 && mbco <= 100 && Number(a.rpoHours) >= 0 && Number(a.troHours) >= rto)) missing.push({ step: 1, label: `${a.name}: complete valid recovery targets in Module 6` });
    if (!s || !t(s.solutionDescription) || !planList(s.selectedStrategies).length) missing.push({ step: 1, label: `${a.name}: define the operational solution in Module 8` });
    else if (!(Number(s.recoveryLeadHours) > 0 && Number(s.recoveryLeadHours) <= rto && Number(s.expectedCapacity) >= mbco)) missing.push({ step: 1, label: `${a.name}: Module 8 solution must meet BIA recovery time and capacity` });
    if (!t(local.instructions)) missing.push({step:3,activityId:a.id,label:`${a.name}: record local execution instructions`});
    if (!t(local.location)) missing.push({ step: 3, activityId: a.id, label: `${a.name}: set the execution location / access instructions` });
    if (!local.stepIds.includes("implement") || !local.stepIds.includes("capacity") || !local.stepIds.includes("restore")) missing.push({ step: 3, activityId: a.id, label: `${a.name}: include implementation, capacity checks and handback steps` });
    if (!local.ownerPersonId || !local.deputyPersonId || local.ownerPersonId === local.deputyPersonId) missing.push({ step: 3, activityId: a.id, label: `${a.name}: assign an owner and a different deputy` });
    personIds.push(local.ownerPersonId, local.deputyPersonId);
  }
  if (!evaluatedPlanHazards(sources.hazards, sources.site?.id).length) missing.push({ step: 0, label: "Evaluate and include the site's hazards in Module 5" });
  if (!planList(data.preparationSelections).length && !t(data.preparationNotes)) missing.push({ step: 2, label: "Define advance preparation arrangements" });
  if (!planList(data.protectionSelections).length && !t(data.protectionNotes)) missing.push({ step: 2, label: "Define immediate welfare, loss prevention and environmental protection arrangements" });
  if (!planList(sources.strategy?.resource_requirements).some((r) => t(r.requirement))) missing.push({ step: 2, label: "Define resource requirements in Module 8" });
  if (!planList(data.reportingSelections).length && !t(data.reportingNotes)) missing.push({ step: 4, label: "Define reporting and decision-log arrangements" });
  if (!t(data.reportingFrequency)) missing.push({ step: 4, label: "Set the reporting frequency" });
  if (!t(data.incomingCommunications)) missing.push({ step: 4, label: "Define how incoming communications are received and escalated" });
  if (!t(data.mediaArrangements)) missing.push({ step: 4, label: "Define the authorised media response or escalation arrangements" });
  if (!t(data.planLocation)) missing.push({ step: 6, label: "Record where offline controlled plan copies are available" });
  if (!t(data.nextReviewDate) || !/^\d{4}-\d{2}-\d{2}$/.test(data.nextReviewDate)) missing.push({ step: 6, label: "Set the next plan review date" });
  if (!data.approverPersonId) missing.push({ step: 6, label: "Select the plan approver" });
  for (const id of [...new Set(personIds.filter(Boolean))]) if (!people.some((p) => p.id === id)) missing.push({ step: 6, label: "A selected person is no longer an active Company User" });
  personIds.push(...planList(sources.strategy?.resource_requirements).map((r)=>r.ownerPersonId));
  const eligibleHazards = new Set(evaluatedPlanHazards(sources.hazards, sources.site?.id).map((r) => r.id));
  for (const row of planList(sources.incident?.activation_thresholds)) if (!eligibleHazards.has(row.scenarioId)) missing.push({ step: 0, label: `Module 9 activation source needs review: ${row.scenario || "Unnamed hazard"}` });
  for (const row of planList(sources.incident?.recovery_stand_down?.scenarioRecovery)) if (!eligibleHazards.has(row.scenarioId) || row.hazardAssessmentId !== sources.hazards?.id) missing.push({ step: 0, label: `Module 9 recovery source needs review: ${row.scenario || "Unnamed hazard"}` });
  for (const key of ["normalOperationsCriteria", "handbackAuthority", "eocClosureCriteria", "standDownProcess", "employeeSupport", "postIncidentReview", "planAvailability"]) if (!t(sources.incident?.recovery_stand_down?.[key])) missing.push({ step: 0, label: `Complete Module 9 recovery arrangements: ${key.replace(/([A-Z])/g, " $1").toLowerCase()}` });
  for (const hazard of evaluatedPlanHazards(sources.hazards, sources.site?.id)) {
    const threshold = planList(sources.incident?.activation_thresholds).find((r) => r.scenarioId === hazard.id);
    const recovery = planList(sources.incident?.recovery_stand_down?.scenarioRecovery).find((r) => r.scenarioId === hazard.id && r.hazardAssessmentId === sources.hazards?.id);
    if (!threshold || !t(threshold.activationCriteria) || !t(threshold.initialControls)) missing.push({ step: 0, label: `${hazard.name}: complete activation thresholds in Module 9` });
    if (!recovery || (!planList(recovery.criteriaSelections).length && !t(recovery.localCriteria))) missing.push({ step: 0, label: `${hazard.name}: complete recovery criteria in Module 9` });
  }
  for (const r of planList(sources.incident?.response_teams)) { personIds.push(r.leadPersonId, r.alternatePersonId); if (!r.leadPersonId || !r.alternatePersonId || !t(r.authority) || !t(r.responsibilities) || !t(r.procedure)) missing.push({step:0,label:`Complete Module 9 response team: ${r.name || "Unnamed team"}`}); }
  for (const r of planList(sources.incident?.warning_communications)) { personIds.push(r.ownerPersonId); if (!r.ownerPersonId || ["what","when","primaryMethod","fallbackMethod","logMethod"].some((key) => !t(r[key]))) missing.push({step:0,label:`Complete Module 9 communications: ${r.audience || "Unnamed audience"}`}); }
  for (const r of planList(sources.incident?.warning_communications)) {
    if (r.emergencyContactKey && !emergencyContactFor(r,sources.site)) missing.push({step:0,label:`Review Module 9 emergency contact link: ${r.audience}`});
    if (r.interestedPartyId && (r.interestedPartyContextId !== sources.context?.id || !planList(sources.context?.interested_parties).some((p)=>p.id===r.interestedPartyId))) missing.push({step:0,label:`Review Module 9 interested party link: ${r.audience}`});
  }
  for (const r of planList(sources.incident?.incident_action_plan)) { personIds.push(r.ownerPersonId); if (r.scenarioScope === "specific" && (r.hazardAssessmentId !== sources.hazards?.id || !planList(r.scenarioIds).length || planList(r.scenarioIds).some((id) => !eligibleHazards.has(id)))) missing.push({step:0,label:`Review Module 9 action scenario links: ${r.action || "Unnamed action"}`}); }
  for (const id of [...new Set(personIds.filter(Boolean))]) if (!people.some((p) => p.id === id) && !missing.some((r) => r.label === "A selected person is no longer an active Company User")) missing.push({step:6,label:"A selected person is no longer an active Company User"});
  for (const r of planList(data.additionalContacts)) if (!t(r.name) || !t(r.contact)) missing.push({step:4,label:"Complete each additional contact's name and contact details, or remove it"});
  if (!planList(sources.incident?.response_teams).length || !planList(sources.incident?.warning_communications).length) missing.push({ step: 0, label: "Complete Module 9 response teams and communications" });
  return missing;
}
export function generateBCPPlan(data, sources, people = [], meta = {}) {
  const site = sources.site, incident = sources.incident || {}, activityRows = planActivityRows(data, sources), hazards = evaluatedPlanHazards(sources.hazards, site?.id), hazardIds = new Set(hazards.map((r) => r.id));
  const person = (id, fallback) => planPerson(id, people, fallback);
  const blocks = (heading, body) => ({ heading, body: t(body) });
  const sections = [];
  sections.push({ id: "purpose", title: "Purpose, scope and objectives", blocks: [blocks("Purpose", data.purpose || `Maintain or restore the selected priority activities at ${site?.location_name || "the selected site"} within their BIA recovery targets.`), blocks("Scope", data.scope), blocks("Site", lines([site?.location_name, site?.address, site?.country])), blocks("Plan accountability", `Owner: ${person(data.planOwnerPersonId)}\nDeputy: ${person(data.deputyPersonId)}\nParticipants: ${planList(data.participantIds).map((id) => person(id)).join("; ") || "None recorded"}`)] });
  sections.push({ id: "priorities", title: "Priority activities and recovery objectives", blocks: activityRows.map(({ activity: a, solution: s }) => blocks(a.name, lines([`Process owner: ${person(a.ownerPersonId, a.owner || "Not assigned")}`, `RTO: ${objective(a, "rtoHours") ?? "Not set"} hours | MTPD: ${objective(a, "mtpdHours") || a.calculated?.detectedMtpdHours || "Not set"} hours`, `Minimum capacity (MBCO): ${a.mbcoPercent ?? "Not set"}% | Full recovery (TRO): ${a.troHours ?? "Not set"} hours | Data recovery (RPO): ${a.rpoHours ?? "Not set"} hours`, `Products / services: ${planList(a.products).join("; ") || a.description || "Not recorded"}`, `Operational solution: ${s?.solutionDescription || "Not defined"}`, `Recovery lead time: ${s?.recoveryLeadHours ?? "Not set"} hours | Expected capacity: ${s?.expectedCapacity ?? "Not set"}%`])))});
  sections.push({ id: "hazards", title: "Site hazards and activation", blocks: [blocks("Invocation process", `The authorised incident controller assesses the impact against the thresholds below, decides which parts of this plan to activate, assigns teams and records the decision. Life safety is the first response priority.\n${data.activationNotes || ""}`), ...hazards.map((r) => { const row = planList(incident.activation_thresholds).find((x) => x.scenarioId === r.id); return blocks(r.name, lines([r.description, `Activation: ${row?.activationCriteria || "Define in Module 9"}`, `Immediate protective actions: ${row?.initialControls || "Define in Module 9"}`, `Response level: ${row?.responseLevel || "Not recorded"}`])); })] });
  sections.push({ id: "teams", title: "Response teams, roles and authority", blocks: planList(incident.response_teams).map((r) => blocks(r.name, lines([`Leader: ${person(r.leadPersonId, r.lead)} | Deputy: ${person(r.alternatePersonId, r.alternate)}`, `Authority: ${r.authority || "Not defined"}`, `Responsibilities: ${r.responsibilities || "Not defined"}`, r.procedure, ...planList(r.additionalMembers).map((m) => `Additional member: ${m.name || ""} | ${m.role || ""} | ${m.organisation || ""} | Contact: ${m.contact || "Not recorded"}`)])))});
  sections.push({id:"actions",title:"Incident action checklist",blocks:planList(incident.incident_action_plan).filter((r) => r.scenarioScope !== "specific" || (r.hazardAssessmentId === sources.hazards?.id && planList(r.scenarioIds).length && planList(r.scenarioIds).every((id) => hazardIds.has(id)))).map((r) => blocks(r.objective || "Incident action", lines([r.action, `Owner: ${person(r.ownerPersonId, r.owner)} | Priority: ${r.priority || "Not set"} | Status at plan issue: ${r.status || "Not set"}`, `Applies to: ${r.scenarioScope === "specific" ? hazards.filter((h) => planList(r.scenarioIds).includes(h.id)).map((h) => h.name).join("; ") : "All included site scenarios"}`, r.dueAt ? `Due: ${r.dueAt}` : ""])))});
  sections.push({ id: "preparation", title: "Preparation, protection, resources and dependencies", blocks: [blocks("Advance arrangements", lines([...planList(data.preparationSelections), data.preparationNotes])), blocks("Immediate protection", lines([...planList(data.protectionSelections), data.protectionNotes])), ...planList(sources.strategy?.resource_requirements).filter((r) => t(r.requirement)).map((r) => blocks(r.type || "Resource", `${r.requirement}\nQuantity: ${r.quantity || "Not recorded"} | Lead time: ${r.leadTimeHours ?? "Not recorded"} hours\nOwner: ${person(r.ownerPersonId, r.owner)}\nBudget: initial ${r.unitCost ?? "Not recorded"}; recurring ${r.recurringCost ?? "Not recorded"} (currency per source arrangement)`)), ...activityRows.map(({ activity: a }) => blocks(`${a.name} BIA resource needs`, planList(a.resources).join("; ") || "Not recorded")), ...planList(sources.outsourced?.supplier_controls).filter((r) => planList(r.activities).some((name) => activityRows.some(({activity:a}) => a.name === name))).map((r) => blocks(`External support: ${r.supplierName}`, lines([r.processDescription, `Process owner: ${r.processOwner || "Not assigned"}`, `Control method: ${r.controlMethod || "Not recorded"}`, `Supplier recovery: ${r.supplierRecoveryHours ?? "Not recorded"} hours`, `Continuity capability evidence: ${r.capabilityEvidence || "Not recorded"}`]))), ...activityRows.map(({ activity: a }) => blocks(`${a.name} dependencies`, planList(a.dependencies).join("; ") || (a.dependencyNotApplicable ? "No additional dependencies declared in BIA" : "Not recorded"))), blocks("Additional interdependencies / resource instructions", data.dependenciesNotes)] });
  sections.push({ id: "playbooks", title: "Activity recovery and restoration procedures", blocks: activityRows.map(({ activity: a, solution: s, local }) => blocks(a.name, lines([`Action owner: ${person(local.ownerPersonId)} | Deputy: ${person(local.deputyPersonId)}`, `Execution location / access: ${local.location || "Not defined"}`, `Operational solution: ${s?.solutionDescription || "Not defined"}`, ...local.stepIds.map((id, index) => { const step = PROCEDURE_STEPS.find(([key]) => key === id); return step ? `${index + 1}. ${step[1]} - ${step[2]}` : ""; }), `Recovery targets: MBCO ${a.mbcoPercent ?? "Not set"}% within RTO ${objective(a, "rtoHours") ?? "Not set"} hours; full recovery within TRO ${a.troHours ?? "Not set"} hours; RPO ${a.rpoHours ?? "Not set"} hours.`, `Local execution instructions: ${local.instructions || "Use the operational solution and assigned arrangements above."}`])))});
  sections.push({ id: "communications", title: "Communications and contact directory", blocks: [blocks("Incoming communications", data.incomingCommunications), blocks("Media arrangements", data.mediaArrangements), ...planList(incident.warning_communications).map((r) => blocks(r.audience || "Audience", lines([`Message: ${r.what || "Not defined"}`, `When: ${r.when || "Not defined"}`, `Owner: ${person(r.ownerPersonId, r.owner)}`, `Primary: ${r.primaryMethod || "Not defined"}\nFallback: ${r.fallbackMethod || "Not defined"}`, `Record: ${r.logMethod || "Not defined"}`]))), ...siteEmergencyContacts(site).map((c) => blocks(c.audience, lines([`Emergency telephone: ${c.emergencyNumber || "Not recorded"}`, `Direct / non-emergency: ${c.nonEmergencyNumber || "Not recorded"}`, c.address, c.accessNotes, c.directionsReference, `Last verified: ${c.lastVerified || "Not recorded"}`]))), ...people.filter((p) => { const ids = [data.planOwnerPersonId, data.deputyPersonId, data.approverPersonId, ...planList(data.participantIds), ...planList(incident.incident_action_plan).map((r)=>r.ownerPersonId), ...activityRows.flatMap(({ local }) => [local.ownerPersonId, local.deputyPersonId]), ...planList(incident.response_teams).flatMap((r) => [r.leadPersonId, r.alternatePersonId]), ...planList(incident.warning_communications).map((r) => r.ownerPersonId)]; return ids.includes(p.id); }).map((p) => blocks(person(p.id), lines([p.position, `Email: ${p.email || "Not recorded"}`, `Telephone: ${p.phone || p.telephone || "Not recorded"}`]))), ...planList(data.additionalContacts).map((c) => blocks(c.name || "Additional contact", lines([c.role, c.organisation, `Contact: ${c.contact || "Not recorded"}`])))] });
  const recovery = incident.recovery_stand_down || {};
  sections.push({ id: "recovery", title: "Operational handback, recovery and stand-down", blocks: [["Common return criteria", Array.isArray(recovery.scenarioRecovery) ? lines([...planList(recovery.selections?.normalOperationsCriteria), recovery.localNotes?.normalOperationsCriteria]) : recovery.normalOperationsCriteria], ...planList(recovery.scenarioRecovery).filter((r) => hazardIds.has(r.scenarioId) && r.hazardAssessmentId === sources.hazards?.id).map((r) => [r.scenario, lines([...planList(r.criteriaSelections), r.localCriteria, r.minimumPeople ? `Minimum people: ${r.minimumPeople}` : "", r.minimumWorkforcePercent ? `Minimum workforce available: ${r.minimumWorkforcePercent}%` : ""])]), ["Handback authority", recovery.handbackAuthority], ["Coordination closure", recovery.eocClosureCriteria], ["Stand-down", recovery.standDownProcess], ["People support", recovery.employeeSupport], ["Post-incident review", recovery.postIncidentReview], ["Additional recovery instructions", data.recoveryNotes]].map(([h, b]) => blocks(h, b)) });
  sections.push({ id: "reporting", title: "Reporting, access and plan maintenance", blocks: [blocks("Reporting and documentation", lines([...planList(data.reportingSelections), data.reportingNotes, `Update frequency: ${data.reportingFrequency || "Not set"}`])), blocks("Controlled plan availability", data.planLocation), blocks("Review and improvement", `Plan owner: ${person(data.planOwnerPersonId)}. Review frequency: ${data.reviewFrequency || "Every 6 months"}. Next review: ${data.nextReviewDate || "Not set"}.\nReview after activation, exercise findings or material changes to people, processes, sites, dependencies or recovery solutions. Record revisions and assign follow-up actions.\n${data.maintenanceNotes || ""}`)] });
  sections.push({ id: "sources", title: "Controlled sources and approval", blocks: [blocks("Plan approval", `Status: ${meta.status || "draft"}\nNominated approver: ${person(data.approverPersonId)}\nApproved at: ${meta.approvedAt || "Not approved"}\nApproval recorded by: ${meta.approvalRecordedBy || "Not approved"}\nReview comment: ${data.reviewComment || "None recorded"}`), ...Object.entries(sources).filter(([, row]) => row).map(([key, row]) => blocks(PLAN_SOURCE_LABELS[key] || key, `${row.assessment_reference || row.profile_reference || row.id} | ${row.assessment_title || row.location_name || ""}\nVersion ${row.version || 1} | Status: ${row.status || "draft"}`))] });
  return { title: data.title || "Business Continuity Plan", organisation: meta.organisation || "", reference: meta.reference || "Draft - reference assigned on save", version: meta.version || 1, status: meta.status || "draft", generatedAt: meta.generatedAt || "Preview - save to create a controlled copy", site: site?.location_name || "", sections };
}
export const PLAN_DOCUMENT_CSS = `.bcpPlanDocument{max-width:1100px;margin:0 auto;background:white;color:#102c47;font:15px/1.6 Arial,sans-serif;padding:35px}.bcpPlanDocument header{padding-bottom:24px;border-bottom:5px solid #315fe6}.bcpPlanDocument h1{font-size:32px;line-height:1.2;margin:10px 0}.bcpPlanDocument .docMeta{display:flex;flex-wrap:wrap;gap:12px;font-size:12px}.bcpPlanDocument section{margin-top:30px}.bcpPlanDocument h2{font-size:23px;border-bottom:1px solid #c9d7e4;padding-bottom:8px}.bcpPlanDocument h3{font-size:16px;margin:18px 0 5px}.bcpPlanDocument p{white-space:pre-wrap;overflow-wrap:anywhere;margin:0 0 12px}.bcpPlanDocument .documentNotice{padding:12px;background:#fff5df;color:#80540b;margin-top:16px}.bcpPlanDocument .docBlock{break-inside:auto}.bcpPlanDocument h2,.bcpPlanDocument h3{break-after:avoid}.bcpPlanDocument footer{margin-top:30px;border-top:1px solid #c9d7e4;padding-top:14px;font-size:11px;color:#52708b}@media(max-width:700px){.bcpPlanDocument{padding:18px}.bcpPlanDocument h1{font-size:26px}}@media print{@page{size:A4;margin:16mm}.bcpPlanDocument{padding:0;max-width:none;font-size:10pt}.bcpPlanDocument h1{font-size:23pt}.bcpPlanDocument h2{font-size:16pt}.bcpPlanDocument h3{font-size:12pt}.bcpProductReturn,.noPrint{display:none!important}body{background:#fff!important}.bcpPlanDocument .documentNotice{border:1px solid #888;background:white;color:#222}}`;
const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
export function planDocumentHtml(doc) { const e = escapeHtml; return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(doc.title)}</title><style>${PLAN_DOCUMENT_CSS}</style></head><body><main class="bcpPlanDocument"><header><small>${e(doc.organisation)} · ${e(doc.site)}</small><h1>${e(doc.title)}</h1><div class="docMeta">${e(doc.reference)} · Version ${e(doc.version)} · ${e(doc.status)} · ${e(doc.generatedAt)}</div>${doc.status !== "approved" ? '<div class="documentNotice">DRAFT / REVIEW COPY — this plan has not been approved.</div>' : ''}</header>${doc.sections.map((s, i) => `<section><h2>${i + 1}. ${e(s.title)}</h2>${s.blocks.filter((b) => b.body).map((b) => `<div class="docBlock"><h3>${e(b.heading)}</h3><p>${e(b.body)}</p></div>`).join("")}</section>`).join("")}<footer>${e(doc.reference)} · v${e(doc.version)} · Controlled copies are maintained at the locations specified in this plan. Check the version before use.</footer></main></body></html>`; }
