const shared = {
  4: { title: "Context of the organisation", application: "Map internal and external issues, interested parties and the boundaries of the management system. Connect this analysis to decisions rather than keeping it as a static document.", evidence: "Context review, interested-party register, scope statement, process map and records showing that changes were considered.", pitfall: "Generic SWOT lists that are not connected to risks, objectives, controls or the defined scope.", support: "RPG Excellence supports facilitated context reviews, scope definition, integrated process mapping and evidence-based gap assessment." },
  5: { title: "Leadership", application: "Make accountability visible through objectives, resources, decisions and routine leadership oversight. Assign responsibilities without transferring top-management accountability.", evidence: "Policy approval, leadership decisions, assigned responsibilities, resource approvals, communications and management-review actions.", pitfall: "Treating the system as the responsibility of one coordinator while operational leaders remain detached.", support: "RPG Excellence supports leadership workshops, governance design, policy alignment and management-review preparation." },
  6: { title: "Planning", application: "Use evidence to identify risks and opportunities, determine obligations, set measurable objectives and plan controlled action with owners, dates and evaluation methods.", evidence: "Risk registers, obligations, objectives, action plans, change assessments and records explaining prioritisation.", pitfall: "Scoring risks without defining actions, accountable owners, timescales or how effectiveness will be evaluated.", support: "RPG Excellence provides risk-based planning, FMEA support, objective setting and three-year assurance programme design." },
  7: { title: "Support", application: "Determine the people, competence, awareness, communication, infrastructure and documented information needed for reliable operation.", evidence: "Competence criteria, training and verification records, communication plans, document controls, resource reviews and retained knowledge.", pitfall: "Using attendance as proof of competence or allowing uncontrolled documents to become the real operating method.", support: "RPG Excellence supports competence frameworks, auditor verification, document architecture and controlled evidence systems." },
  8: { title: "Operation", application: "Translate planned controls into repeatable operational practice, including outsourced activities, procurement, change and abnormal or emergency conditions.", evidence: "Operational criteria, work controls, supplier controls, change records, inspection results, exercise records and retained operational evidence.", pitfall: "Procedures that describe an ideal process but do not match actual work, interfaces or outsourced activities.", support: "RPG Excellence supports process control reviews, multisite audits, supplier assurance and practical operational-control design." },
  9: { title: "Performance evaluation", application: "Define what must be monitored, analysed, audited and reviewed so leaders can determine whether the system is suitable, effective and delivering intended outcomes.", evidence: "Meaningful KPIs, evaluation results, internal-audit records, compliance reviews, trend analysis and management-review outputs.", pitfall: "Reporting activity counts without evaluating performance, trends, control effectiveness or the causes of weak results.", support: "RPG Excellence provides clause-based assessments, integrated internal audits, dashboards and management-ready assurance reporting." },
  10: { title: "Improvement", application: "Control incidents and nonconformities, investigate proportionately, correct causes and verify that improvements are effective and sustained.", evidence: "Corrections, cause analysis, CAPA-8D records, effectiveness checks, lessons learned and updated risks or controls.", pitfall: "Closing actions when tasks are completed rather than when objective evidence demonstrates sustained effectiveness.", support: "RPG Excellence connects findings to CAPA-8D, accountable actions and independent effectiveness verification." },
};

const guides = {
  "iso-9001": { code: "ISO 9001", edition: "2015 / Amendment 1:2024", title: "Quality Management", accent: "blue", summary: "Build consistent processes, dependable outputs and customer confidence through a management system that turns evidence into improvement.", purpose: "A practical framework for controlling processes, meeting customer and applicable requirements, and improving quality performance.", focus: { 4:"Business context, customers, relevant interested parties, QMS scope and the processes needed to deliver conforming products and services.",5:"Customer focus, quality policy, process ownership and leadership accountability for QMS effectiveness.",6:"Quality risks and opportunities, customer requirements, measurable objectives and controlled planning of change.",7:"Process resources, monitoring equipment, organisational knowledge, competence, awareness, communication and documented information.",8:"Requirements review, design where applicable, supplier control, production or service delivery, release and control of nonconforming outputs.",9:"Customer perception, process performance, product or service conformity, internal audit and management review.",10:"Nonconformity, corrective action and continual improvement of products, services, processes and the QMS." } },
  "iso-14001": { code: "ISO 14001", edition: "Environmental management system", title: "Environmental Management", accent: "green", summary: "Control environmental aspects and compliance obligations while improving environmental performance across the life cycle.", purpose: "A risk-based framework for managing environmental impacts, obligations, operational controls and continual improvement.", focus: { 4:"Environmental conditions, interested parties, compliance context, EMS boundaries and activities within the organisation's control or influence.",5:"Leadership commitment, environmental policy and integration of environmental responsibilities into business processes.",6:"Environmental aspects, compliance obligations, risks and opportunities, objectives and planning that considers a life-cycle perspective.",7:"Environmental competence, awareness, internal and external communication, resources and controlled documented information.",8:"Operational controls for significant aspects, procurement and outsourced processes, change and emergency preparedness and response.",9:"Monitoring environmental performance, evaluating compliance, internal audit and management review.",10:"Environmental incidents and nonconformities, corrective action and continual improvement of environmental performance." } },
  "iso-45001": { code: "ISO 45001", edition: "2018 / Amendment 1:2024", title: "Occupational Health & Safety", accent: "orange", summary: "Prevent work-related injury and ill health through leadership, worker participation and effective control of OH&S risks.", purpose: "A framework for eliminating hazards, reducing OH&S risks and continually improving safe and healthy work.", focus: { 4:"OH&S context, workers and other interested parties, system scope and the activities and interfaces that can affect health and safety.",5:"Leadership accountability, OH&S policy, organisational roles and meaningful consultation and participation of workers.",6:"Hazard identification, OH&S risk and opportunity assessment, legal and other requirements, objectives and planning of change.",7:"Resources, competence, awareness, worker communication and controlled health-and-safety information.",8:"Hierarchy of controls, management of change, procurement, contractors, outsourcing and emergency preparedness and response.",9:"OH&S monitoring, legal-compliance evaluation, internal audit, worker input and management review.",10:"Incident and nonconformity control, worker involvement in investigation, corrective action and improvement of OH&S performance." } },
  "iso-22301": { code: "ISO 22301", edition: "2019 / Amendment 1:2024", title: "Business Continuity", accent: "purple", summary: "Protect priority activities by understanding disruption impacts, preparing workable responses and exercising recovery arrangements.", purpose: "A structured approach to organisational resilience, business-impact analysis, continuity strategies and tested response capability.", focus: { 4:"Disruption context, interested parties, legal and contractual expectations, BCMS scope and dependencies across priority activities.",5:"Continuity policy, leadership commitment, crisis governance and clear authority before, during and after disruption.",6:"Risks and opportunities affecting the BCMS, continuity objectives and controlled planning for changes.",7:"Continuity resources, competent response roles, awareness, communications capability and controlled plans and records.",8:"Business-impact analysis, risk assessment, continuity strategies, plans and procedures, exercise programmes and evaluation of capability.",9:"Monitoring continuity capability, exercise and test results, internal audit and management review.",10:"Learning from disruptions, exercises and nonconformities, corrective action and continual improvement of resilience." } },
  "iso-27001": { code: "ISO/IEC 27001", edition: "2022 / Amendment 1:2024", title: "Information Security", accent: "teal", summary: "Manage information-security risk through proportionate controls, accountable governance and continual evaluation of the ISMS.", purpose: "A risk-based framework for protecting the confidentiality, integrity and availability of information.", focus: { 4:"Information-security context, interested parties, regulatory and contractual needs, ISMS scope, interfaces and dependencies.",5:"Information-security policy, leadership accountability and clear roles for risk ownership and security governance.",6:"Information-security risk assessment and treatment, objectives, planned changes and maintenance of the Statement of Applicability.",7:"Security resources, competence, awareness, communication and controlled documented information.",8:"Repeatable risk assessment and treatment processes, implementation of selected controls and retained evidence of operation.",9:"Security monitoring, measurement, internal audit, management review and evaluation of whether controls and the ISMS are effective.",10:"Security nonconformities, corrective action, lessons from events and continual improvement of the ISMS." } },
};

export function getStandardGuide(slug) {
  const guide = guides[slug];
  if (!guide) return null;
  return { ...guide, slug, clauses: Object.keys(shared).map((number) => ({ number, ...shared[number], focus: guide.focus[number] })) };
}
