import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "../../../../../lib/supabase/server";

export const dynamic = "force-dynamic";

export default async function BCPPostersPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/signin");

  return <main className="bpPage">
    <header className="bpTop noPrint"><div><span>BCP LEARNING RESOURCES</span><h1>Business continuity posters</h1><p>Display these prompts where teams plan, operate and exercise recovery.</p></div><div><Link href="/portal/business-continuity/training">← Learning path</Link><span className="bpPrint">Use your browser’s Print command</span></div></header>

    <section className="bpPoster bpBlue"><div className="bpTag">POSTER 01 · SITE PROFILE</div><h2>Protect what must continue.</h2><p className="bpLead">Start with the value chain—not the organisation chart.</p><div className="bpFlow"><b>Inputs</b><i>→</i><b>Value-creating processes</b><i>→</i><b>Products &amp; services</b><i>→</i><b>Customers</b></div><div className="bpColumns"><article><h3>Ask</h3><p>Which activities directly create or deliver the priority product or service?</p></article><article><h3>Connect</h3><p>People · premises · technology · data · utilities · suppliers · communications</p></article><article><h3>Own</h3><p>Name a process owner and recovery decision-maker for every critical process.</p></article></div><footer>RPG Excellence · Business Continuity Planning</footer></section>

    <section className="bpPoster bpAmber"><div className="bpTag">POSTER 02 · IMPACT &amp; RECOVERY</div><h2>Time changes the impact.</h2><p className="bpLead">Set recovery objectives from business need, then validate that resources and strategies can achieve them.</p><div className="bpTimeline"><span>Disruption</span><span>RTO<br/><small>Target restoration</small></span><span>MTPD<br/><small>Maximum tolerable period</small></span></div><div className="bpColumns"><article><h3>Prioritise</h3><p>Safety, legal duties, customers, financial exposure, reputation and dependencies.</p></article><article><h3>Define</h3><p>Minimum acceptable capacity, data recovery needs and required resources.</p></article><article><h3>Challenge</h3><p>Can the proposed solution work during the disruption—not only on paper?</p></article></div><footer>RPG Excellence · Business Continuity Planning</footer></section>

    <section className="bpPoster bpGreen"><div className="bpTag">POSTER 03 · EXERCISE &amp; IMPROVE</div><h2>A plan becomes credible when exercised.</h2><p className="bpLead">Use realistic objectives, observable evidence and owned improvements.</p><div className="bpCycle"><b>Plan</b><i>→</i><b>Exercise</b><i>→</i><b>Observe</b><i>→</i><b>Improve</b><i>↻</i></div><div className="bpColumns"><article><h3>Before</h3><p>Agree scope, scenario, objectives, participants, safety controls and success criteria.</p></article><article><h3>During</h3><p>Record decisions, communications, timings, constraints, workarounds and evidence.</p></article><article><h3>After</h3><p>Assign actions, verify effectiveness and update plans, training and assumptions.</p></article></div><footer>RPG Excellence · Business Continuity Planning</footer></section>

    <style>{`*{box-sizing:border-box}.bpPage{background:#eaf1f8;min-height:100vh;padding:36px;color:#0b2346;font-family:Arial,sans-serif}.bpTop{max-width:1120px;margin:0 auto 28px;display:flex;justify-content:space-between;gap:24px;align-items:end}.bpTop>div:first-child>span,.bpTag{font-size:12px;font-weight:900;letter-spacing:.14em;color:#2458e6}.bpTop h1{font-size:38px;margin:8px 0}.bpTop p{color:#526b89}.bpTop div:last-child{display:flex;gap:10px;align-items:center}.bpTop a,.bpPrint{border:1px solid #bed0e4;border-radius:9px;background:white;color:#153a70;padding:11px 14px;font-weight:800;text-decoration:none}.bpPoster{max-width:1120px;min-height:650px;margin:0 auto 34px;border-radius:24px;padding:62px;position:relative;overflow:hidden;box-shadow:0 20px 45px #17395d20;background:white}.bpPoster:after{content:"";position:absolute;width:380px;height:380px;border:70px solid currentColor;border-radius:50%;right:-170px;top:-170px;opacity:.08}.bpPoster h2{font-size:58px;line-height:1;margin:30px 0 18px;max-width:780px}.bpLead{font-size:23px;line-height:1.5;max-width:830px}.bpFlow,.bpCycle{margin:56px 0 44px;padding:24px;border-radius:16px;background:#f2f7fc;display:flex;justify-content:center;align-items:center;gap:25px;font-size:19px;text-align:center}.bpFlow i,.bpCycle i{font-size:30px;color:#2860ea}.bpColumns{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.bpColumns article{border:1px solid #cadaea;border-radius:15px;padding:22px;background:#fff}.bpColumns h3{margin:0 0 10px;font-size:20px}.bpColumns p{margin:0;line-height:1.55;color:#3e5876}.bpTimeline{display:grid;grid-template-columns:1fr 1fr 1fr;align-items:center;margin:58px 0 45px;padding-top:14px;border-top:8px solid #f0a026}.bpTimeline span{position:relative;font-size:18px;font-weight:900;padding-top:18px}.bpTimeline span:before{content:"";position:absolute;top:-20px;width:25px;height:25px;border-radius:50%;background:#f0a026}.bpTimeline small{font-weight:500;color:#526b89}.bpPoster footer{position:absolute;bottom:27px;left:62px;font-size:12px;font-weight:800;letter-spacing:.08em}.bpAmber .bpTag{color:#bd6c00}.bpGreen .bpTag{color:#087b62}.bpGreen .bpCycle i{color:#079174}@media(max-width:800px){.bpPage{padding:18px}.bpTop{display:block}.bpTop div:last-child{margin-top:15px}.bpPoster{padding:32px;min-height:auto}.bpPoster h2{font-size:40px}.bpFlow,.bpCycle{flex-wrap:wrap}.bpColumns{grid-template-columns:1fr}.bpPoster footer{position:static;margin-top:30px}}@media print{.noPrint{display:none}.bpPage{background:white;padding:0}.bpPoster{box-shadow:none;border-radius:0;margin:0;min-height:100vh;page-break-after:always;padding:18mm}.bpPoster:last-of-type{page-break-after:auto}.bpPoster footer{left:18mm;bottom:14mm}}`}</style>
  </main>;
}
