import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "../../../../../lib/supabase/server";
import { createAdminClient } from "../../../../../lib/supabase/admin";
import { getAssessmentAccessState } from "../../../../../lib/assessment-access";
import { calculateProgress, calculateSimpleOverallScore } from "../scoring";
import { generateAssessmentExecutiveDraft, saveAssessmentExecutiveReport } from "./actions";

const field = { width:"100%", border:"1px solid #cbd8e8", borderRadius:"8px", padding:"11px 12px", background:"#fff", color:"#071a33", font:"inherit", boxSizing:"border-box" };
const labelStyle = { display:"grid", gap:"7px", color:"#203b5d", fontSize:"14px", fontWeight:800 };
const maturity = (score) => score === null ? "Not assessed" : score <= 20 ? "Initial" : score <= 40 ? "Developing" : score <= 60 ? "Managed" : score <= 80 ? "Controlled" : "Optimised";
function Metric({ label, value, note, tone="#071a33" }) { return <div className="gerMetric"><span>{label}</span><strong style={{color:tone}}>{value}</strong><small>{note}</small></div>; }

export default async function AssessmentExecutiveReportPage({ params, searchParams }) {
  const { id } = await params, query = await searchParams;
  const supabase = await createClient(), admin = createAdminClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect(`/portal/login?next=/portal/assessments/${id}/executive-report`);
  const { data: assessment } = await supabase.from("assessments").select("*").eq("id", id).eq("owner_id", user.id).single();
  if (!assessment) redirect("/portal");
  const access = await getAssessmentAccessState(user.id, id);
  const [{ data: questions }, { data: answers }, { data: findings }, { data: report }] = await Promise.all([
    supabase.from("assessment_questions").select("question_number,clause").eq("standard", assessment.standard).eq("active", true),
    supabase.from("assessment_answers").select("clause,score").eq("assessment_id", id).eq("owner_id", user.id),
    admin.from("assessment_findings").select("finding_type,status,risk_impact").eq("assessment_id", id).eq("owner_id", user.id).neq("finding_type", "conformity"),
    admin.from("assessment_executive_reports").select("*").eq("assessment_id", id).eq("owner_id", user.id).maybeSingle(),
  ]);
  const progress = calculateProgress(questions || [], answers || []), score = calculateSimpleOverallScore(answers || []);
  const open = (findings || []).filter((x) => !["closed","withdrawn"].includes(x.status));
  const major = open.filter((x) => x.finding_type === "major_nc").length, minor = open.filter((x) => x.finding_type === "minor_nc").length;
  const reference = report?.report_reference || `GAR-${id.replaceAll("-","").slice(0,8).toUpperCase()}-RPT`;
  const hasNarrative = Boolean(report?.executive_summary && report?.overall_conclusion);

  return <main className="gerPage"><style>{`
    *{box-sizing:border-box}.gerPage{min-height:100vh;background:#f3f6f9;padding:36px 20px 75px;font-family:Arial,sans-serif;color:#071a33}.gerWrap{max-width:1280px;margin:auto}.gerHead{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;flex-wrap:wrap;margin-bottom:20px}.gerHead small{color:#1459d9;font-weight:900;letter-spacing:.08em}.gerHead h1{font-size:36px;margin:7px 0}.gerHead p{margin:0;color:#617087}.gerActions{display:flex;gap:9px;flex-wrap:wrap}.gerButton{display:inline-flex;padding:11px 15px;border:1px solid #cbd8e8;border-radius:8px;background:#fff;color:#071a33;text-decoration:none;font-weight:800}.gerButton.blue{background:#1459d9;color:#fff;border-color:#1459d9}.gerButton.navy{background:#071a33;color:#fff;border-color:#071a33}.gerHero{display:flex;justify-content:space-between;align-items:center;gap:20px;flex-wrap:wrap;padding:27px;border-radius:16px;background:#071a33;color:#fff}.gerHero span{font-size:12px;font-weight:800;opacity:.72;letter-spacing:.06em}.gerHero h2{margin:7px 0 4px}.gerHero strong{font-size:58px}.gerMetrics{display:grid;grid-template-columns:repeat(5,1fr);gap:11px;margin:14px 0 18px}.gerMetric{padding:17px;border:1px solid #d8e2ee;border-radius:12px;background:#fff}.gerMetric span,.gerMetric small{display:block;color:#657990}.gerMetric span{font-size:11px;font-weight:900;text-transform:uppercase}.gerMetric strong{display:block;font-size:27px;margin:7px 0}.gerMetric small{font-size:12px}.gerPanel{overflow:hidden;border:1px solid #d8e2ee;border-radius:15px;background:#fff}.gerPanelHead{display:flex;justify-content:space-between;gap:18px;align-items:center;flex-wrap:wrap;padding:20px 22px;border-bottom:1px solid #e2e9f1}.gerPanelHead h2{margin:5px 0}.gerPanelHead p{margin:0;color:#617087}.gerDraft{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.gerForm{padding:22px}.gerGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.span2{grid-column:span 2}.gerSave{margin-top:17px;border:0;border-radius:8px;padding:12px 17px;background:#1459d9;color:#fff;font-weight:900;cursor:pointer}.gerNotice{margin-bottom:16px;padding:13px 15px;border:1px solid #b9dfcc;border-radius:10px;background:#edf8f3;color:#12613f;font-weight:800}@media(max-width:850px){.gerMetrics{grid-template-columns:repeat(2,1fr)}.gerGrid{grid-template-columns:1fr}.span2{grid-column:auto}}@media(max-width:520px){.gerMetrics{grid-template-columns:1fr 1fr}.gerHead h1{font-size:29px}}
  `}</style><div className="gerWrap">
    <header className="gerHead"><div><small>RPG INTELLIGENCE · CONTROLLED GAP REPORT</small><h1>Gap Assessment Executive Report</h1><p>{assessment.standard} · {reference} · status <strong>{report?.report_status || "draft"}</strong></p></div><div className="gerActions"><Link className="gerButton" href={`/portal/assessments/${id}`}>← Assessment</Link><Link className="gerButton" href={`/portal/assessments/${id}/summary`}>Analysis</Link><a className="gerButton blue" href={`/portal/assessments/${id}/executive-report/pdf`} target="_blank" rel="noreferrer">Preview / Download PDF</a><Link className="gerButton navy" href={`/portal/assessments/${id}/findings`}>Findings &amp; actions</Link></div></header>
    {(query?.saved || query?.generated) && <div className="gerNotice">{query.generated ? "Guided executive-report draft created. Review and take ownership before approval." : "Controlled executive report saved."}</div>}
    <section className="gerHero"><div><span>BUSINESS ASSURANCE POSITION</span><h2>{progress.percentage < 100 ? "Assessment incomplete" : major ? "Management intervention required" : score >= 80 ? "Potentially ready" : "Improvement required"}</h2><div>{progress.answered} of {progress.total} requirements assessed</div></div><strong>{score === null ? "—" : `${score}%`}</strong></section>
    <section className="gerMetrics"><Metric label="Progress" value={`${progress.percentage}%`} note={`${progress.total-progress.answered} unanswered`} tone="#1459d9"/><Metric label="Maturity" value={maturity(score)} note="Current evidence position"/><Metric label="Open findings" value={open.length} note="Controlled follow-up" tone={open.length?"#b42318":"#087a52"}/><Metric label="Major NC" value={major} note="Systemic significance" tone={major?"#b42318":"#087a52"}/><Metric label="Minor NC" value={minor} note="Limited nonconformity" tone={minor?"#a55a09":"#087a52"}/></section>
    <section className="gerPanel"><div className="gerPanelHead"><div><small style={{color:"#1459d9",fontWeight:900}}>REPORT CONTENT AND REVIEW</small><h2>Controlled executive report</h2><p>Generate from live assessment results, then review, edit and approve responsibly.</p></div>{access.canEditAssessment && <form className="gerDraft" action={generateAssessmentExecutiveDraft}><input type="hidden" name="assessment_id" value={id}/><label><input type="checkbox" name="replace_existing"/> Replace existing narrative</label><button className="gerButton blue">Build guided draft</button></form>}</div>
      {!hasNarrative && <div style={{padding:"14px 22px",background:"#fff7e7",color:"#805500",fontWeight:800}}>Select Build guided draft to create the first controlled narrative from current assessment results.</div>}
      <form className="gerForm" action={saveAssessmentExecutiveReport}><input type="hidden" name="assessment_id" value={id}/><fieldset disabled={!access.canEditAssessment} style={{border:0,padding:0,margin:0}}><div className="gerGrid">
        <label style={labelStyle}>Report reference<input name="report_reference" defaultValue={reference} style={field}/></label><label style={labelStyle}>Confidentiality<select name="confidentiality" defaultValue={report?.confidentiality||"Internal"} style={field}><option>Internal</option><option>Confidential</option><option>Restricted</option><option>Client controlled</option></select></label><label style={labelStyle}>Report status<select name="report_status" defaultValue={report?.report_status||"draft"} style={field}><option value="draft">Draft</option><option value="under_review">Under review</option><option value="approved">Approved</option><option value="issued">Issued</option></select></label>
        <label className="span2" style={labelStyle}>Executive summary<textarea name="executive_summary" defaultValue={report?.executive_summary||""} rows={6} style={field}/></label><label style={labelStyle}>Distribution list<textarea name="distribution_list" defaultValue={report?.distribution_list||""} rows={6} style={field}/></label>
        <label className="span2" style={labelStyle}>Methodology and sampling<textarea name="methodology_and_sampling" defaultValue={report?.methodology_and_sampling||""} rows={6} style={field}/></label><label style={labelStyle}>Limitations and exclusions<textarea name="limitations_and_exclusions" defaultValue={report?.limitations_and_exclusions||""} rows={6} style={field}/></label>
        <label style={labelStyle}>Priority actions<textarea name="priority_actions" defaultValue={report?.priority_actions||""} rows={6} style={field}/></label><label className="span2" style={labelStyle}>Overall conclusion<textarea name="overall_conclusion" defaultValue={report?.overall_conclusion||""} rows={6} style={field}/></label>
        <label style={labelStyle}>Prepared by<input name="prepared_by" defaultValue={report?.prepared_by||user.email||""} style={field}/></label><label style={labelStyle}>Reviewed by<input name="reviewed_by" defaultValue={report?.reviewed_by||""} style={field}/></label><label style={labelStyle}>Approved by<input name="approved_by" defaultValue={report?.approved_by||""} style={field}/></label>
      </div>{access.canEditAssessment && <button className="gerSave">Save controlled report</button>}</fieldset></form>
    </section>
  </div></main>;
}
