-- ISO 22301:2019 Business Continuity Management System gap assessment.
-- Requirement summaries are assessment prompts derived from the supplied standard.

delete from public.assessment_questions where standard = 'ISO 22301:2019';

with requirements as (
  select * from jsonb_to_recordset($requirements$
  [
    {"n":"4.1","c":"4","q":"Has the organisation determined the external and internal issues relevant to its purpose and affecting the intended outcomes of the BCMS?","s":"Determine and keep under review the context that can affect business continuity outcomes.","e":"Context analysis; strategic and operational risk reviews; disruption history; dependency and threat intelligence; evidence of periodic review."},
    {"n":"4.2.1","c":"4","q":"Has the organisation determined the interested parties relevant to the BCMS and their relevant requirements?","s":"Identify relevant interested parties and the needs and expectations that influence continuity arrangements.","e":"Interested-party register; customer and stakeholder requirements; contracts; service commitments; community and supply-chain expectations."},
    {"n":"4.2.2","c":"4","q":"Are applicable legal and regulatory requirements identified, accessible, evaluated and reflected in the BCMS?","s":"Establish, maintain and apply a process for relevant legal and regulatory continuity obligations.","e":"Legal register; regulatory correspondence; licence conditions; contractual obligations; compliance evaluations; records of changes and resulting actions."},
    {"n":"4.3.1","c":"4","q":"Were the organisation's context, interested-party requirements, mission, objectives and obligations considered when determining the BCMS scope?","s":"Use relevant organisational and stakeholder factors to establish defensible BCMS boundaries.","e":"Approved scope rationale; context and stakeholder inputs; organisational structure; locations, functions, services and dependencies considered."},
    {"n":"4.3.2","c":"4","q":"Does the documented BCMS scope clearly define its boundaries and applicability, identify included products and services, and explain exclusions?","s":"Maintain a clear documented scope that identifies covered products and services and justifies exclusions without weakening continuity capability.","e":"Controlled BCMS scope statement; product and service catalogue; sites and functions; interface map; justified exclusions and approval records."},
    {"n":"4.4","c":"4","q":"Is a BCMS established, implemented, maintained and continually improved through the processes and interactions needed by ISO 22301?","s":"Operate an integrated business continuity management system rather than a collection of isolated plans.","e":"BCMS process map; governance framework; procedures; process owners; performance information; review and improvement records."},

    {"n":"5.1","c":"5","q":"Can top management demonstrate leadership and commitment to the BCMS and its intended outcomes?","s":"Top management remains accountable for BCMS effectiveness, integration, resources, communication, support and continual improvement.","e":"Leadership decisions; budgets and resources; governance minutes; objectives; management communications; performance challenge; participation in exercises and reviews."},
    {"n":"5.2.1","c":"5","q":"Has top management established a business continuity policy appropriate to the organisation and supportive of objectives and applicable requirements?","s":"Establish a policy providing purpose, direction and commitments to requirements and continual improvement.","e":"Approved policy; alignment with purpose and strategy; commitments; review history; links to objectives and BCMS governance."},
    {"n":"5.2.2","c":"5","q":"Is the business continuity policy controlled, communicated, understood, applied and available to relevant interested parties?","s":"Maintain the policy as documented information and ensure it is understood and available as appropriate.","e":"Controlled policy; induction and briefing records; awareness sampling; intranet/publication evidence; stakeholder distribution."},
    {"n":"5.3","c":"5","q":"Are BCMS roles, responsibilities and authorities assigned, communicated and reported to top management?","s":"Ensure accountability for conformity and for reporting BCMS performance is clear.","e":"Organisation charts; role profiles; RACI; incident command authorities; deputies; reporting routes; committee terms of reference."},

    {"n":"6.1.1","c":"6","q":"Has the organisation determined BCMS risks and opportunities arising from context and stakeholder requirements?","s":"Identify what could affect intended outcomes, prevent undesirable effects or enable improvement of the BCMS.","e":"BCMS risk and opportunity register; context linkage; criteria; owners; treatment priorities; review records."},
    {"n":"6.1.2","c":"6","q":"Are actions for BCMS risks and opportunities planned, integrated, implemented and evaluated for effectiveness?","s":"Convert risk and opportunity decisions into controlled action within BCMS processes and evaluate results.","e":"Action plans; process integration; owners and dates; completion evidence; effectiveness reviews; residual-risk decisions."},
    {"n":"6.2.1","c":"6","q":"Are business continuity objectives established at relevant functions and levels and controlled as documented information?","s":"Set objectives that are consistent with policy, measurable where practicable, monitored, communicated and updated.","e":"Approved objective register; KPIs; baselines and targets; monitoring; communication; review and revision records."},
    {"n":"6.2.2","c":"6","q":"Does planning to achieve each business continuity objective define actions, resources, ownership, timescales and evaluation of results?","s":"Translate objectives into deliverable plans with accountable ownership and evaluation methods.","e":"Objective delivery plans; resource approvals; accountable owners; milestones; measures; progress and outcome reviews."},
    {"n":"6.3","c":"6","q":"Are changes to the BCMS carried out in a planned and controlled manner?","s":"Plan BCMS changes by considering purpose, consequences, system integrity, resources and responsibilities.","e":"Change requests; impact and risk assessments; approvals; implementation plans; communications; post-change verification."},

    {"n":"7.1","c":"7","q":"Are the resources needed to establish, implement, maintain and continually improve the BCMS determined and provided?","s":"Provide sufficient people, finance, facilities, technology, information and external support for continuity capability.","e":"Resource plans; budgets; staffing and deputy arrangements; facilities and technology; supplier support; capability gap actions."},
    {"n":"7.2","c":"7","q":"Are people performing BCMS work competent on the basis of appropriate education, training or experience, with evidence retained?","s":"Determine competence, close gaps, evaluate actions and retain evidence of competence.","e":"Competence criteria; training needs analysis; role-based training; exercise performance; qualifications; competence evaluation records."},
    {"n":"7.3","c":"7","q":"Are relevant persons aware of the policy, their contribution, the benefits of improved performance and the implications of not conforming?","s":"Build role-relevant awareness so personnel understand how their actions support continuity outcomes.","e":"Awareness programme; induction; role briefings; interviews; exercise observations; communications; understanding checks."},
    {"n":"7.4","c":"7","q":"Has the organisation determined what, when, with whom and how to communicate internally and externally about the BCMS?","s":"Plan controlled BCMS communications, including content, timing, audience, method and responsibility.","e":"Communication strategy; stakeholder matrix; escalation routes; spokesperson arrangements; notification templates; contact lists and tests."},
    {"n":"7.5.1","c":"7","q":"Does the BCMS include all documented information required by ISO 22301 and that determined necessary by the organisation?","s":"Maintain sufficient documented information for effective BCMS operation and assurance.","e":"BCMS document hierarchy; mandatory records matrix; procedures and plans; retained evidence; documented-information needs analysis."},
    {"n":"7.5.2","c":"7","q":"Are BCMS documents appropriately identified, described, formatted, reviewed and approved when created or updated?","s":"Apply suitable identification, format, media, review and approval controls.","e":"Document templates; metadata; version history; review and approval records; controlled issue and update workflow."},
    {"n":"7.5.3","c":"7","q":"Is documented information available, suitable, protected and controlled throughout its distribution, access, storage, change, retention and disposition?","s":"Control BCMS documented information, including external documents, while preserving availability during disruption.","e":"Document-control procedure; access controls; backup and offline availability; retention schedule; change history; external-document register; disposal records."},

    {"n":"8.1","c":"8","q":"Are BCMS operational processes planned, implemented and controlled using criteria, retained evidence and controlled change and outsourcing?","s":"Operate the processes needed to meet BCMS requirements and implement planned actions, including control of changes and outsourced processes.","e":"Operational procedures; criteria; work records; planned and unintended change reviews; outsourced-process controls; supplier assurance."},
    {"n":"8.2.1","c":"8","q":"Are business impact analysis and risk assessment processes implemented, maintained and reviewed at planned intervals and when significant changes occur?","s":"Use defined, repeatable BIA and risk-assessment processes that remain current.","e":"BIA and risk methodologies; review schedule; change triggers; completed analyses; approval and version records."},
    {"n":"8.2.2a","c":"8","r":"8.2.2 a)-c)","q":"Does the BIA define impact types and criteria, identify activities supporting products and services, and assess impacts over time?","s":"Analyse how disruption impacts develop and which activities support delivery of products and services.","e":"Approved impact criteria; service and activity maps; impact-over-time analysis; financial, operational, legal, safety, reputational and stakeholder impacts."},
    {"n":"8.2.2b","c":"8","r":"8.2.2 d)-f)","q":"Does the BIA identify when impacts become unacceptable, set prioritised time frames for resumption and identify prioritised activities?","s":"Use justified impact thresholds to determine recovery priorities and time frames.","e":"Maximum tolerable periods of disruption; recovery time objectives; minimum service levels; prioritised activity list; management approval and rationale."},
    {"n":"8.2.2c","c":"8","r":"8.2.2 g)-h)","q":"Does the BIA determine the resources and dependencies needed by prioritised activities, including partners and suppliers?","s":"Identify resources and dependencies required to resume and maintain prioritised activities.","e":"People, premises, technology, information, finance and supplier requirements; dependency maps; single points of failure; resource recovery objectives."},
    {"n":"8.2.3","c":"8","q":"Does the risk assessment identify, analyse and evaluate disruption risks to prioritised activities and required resources, and select appropriate treatments?","s":"Assess disruption risks systematically and determine treatments consistent with risk appetite and continuity requirements.","e":"Risk criteria; disruption scenarios; dependency and resource risks; risk register; existing controls; treatment plans; residual-risk acceptance."},
    {"n":"8.3.1","c":"8","q":"Are business continuity strategies and solutions based on BIA and risk-assessment outputs?","s":"Use approved continuity requirements and risk information as the basis for continuity choices.","e":"Traceability from BIA and risk assessment to strategy; decision records; scenario coverage; management approval."},
    {"n":"8.3.2","c":"8","q":"Are strategies and solutions identified for before, during and after disruption to protect, stabilise, continue, resume, recover, mitigate and respond?","s":"Identify feasible options that address the full disruption timeline and continuity requirements.","e":"Options appraisal; prevention and resilience measures; response and workaround options; recovery solutions; supplier and reciprocal arrangements."},
    {"n":"8.3.3","c":"8","q":"Are strategies and solutions selected using defined criteria including continuity requirements, risk, benefit and cost?","s":"Select and approve solutions using transparent and proportionate decision criteria.","e":"Selection criteria; option evaluations; cost-benefit and risk analysis; capability assumptions; approvals; rejected-option rationale."},
    {"n":"8.3.4","c":"8","q":"Are resource requirements determined for selected continuity solutions?","s":"Determine the people, information, data, infrastructure, equipment, consumables, finance, transport, logistics, partners and suppliers needed.","e":"Resource requirement schedules; minimum staffing; technology and data recovery needs; alternate premises; inventories; finance and supplier commitments."},
    {"n":"8.3.5","c":"8","q":"Are selected business continuity solutions implemented and maintained so they can be activated when needed?","s":"Turn approved strategies into operational capability with controlled implementation and maintenance.","e":"Implemented solutions; contracts; configurations; standby arrangements; readiness checks; maintenance records; assigned ownership."},
    {"n":"8.4.1","c":"8","q":"Are business continuity plans and procedures established, implemented and maintained to manage disruption and continue and recover priority activities?","s":"Maintain usable response and recovery arrangements that meet continuity requirements and account for dependencies.","e":"Controlled plans and procedures; activation criteria; assumptions; dependencies; access arrangements; version control; exercise and incident use."},
    {"n":"8.4.2.1","c":"8","q":"Is a response structure with competent teams established and maintained for disruptive incidents?","s":"Identify teams with authority and capability to assess, activate, respond and manage consequences.","e":"Incident response structure; team charters; membership and deputies; competence records; command locations; activation and escalation arrangements."},
    {"n":"8.4.2.2","c":"8","q":"Are team roles, responsibilities and relationships clearly defined?","s":"Document how response teams coordinate, escalate, hand over and account for decisions.","e":"RACI; team plans; reporting lines; escalation and handover protocols; interface maps; role cards."},
    {"n":"8.4.2.3","c":"8","q":"Can response teams collectively assess incidents, activate response, prioritise life safety, manage consequences, communicate and preserve relevant information?","s":"Demonstrate the full set of response competencies required during disruption.","e":"Exercise observations; incident logs; decision records; safety actions; situation reports; communication records; post-incident evidence preservation."},
    {"n":"8.4.2.4","c":"8","q":"Does each response team have documented activation thresholds, procedures, meeting locations and communication methods?","s":"Provide each team with actionable and accessible operating arrangements.","e":"Team plans; activation criteria; call-out lists; virtual and physical meeting arrangements; alternate communications; tested contact data."},
    {"n":"8.4.3.1","c":"8","q":"Are warning and communication procedures documented and maintained for internal and external stakeholders during disruption?","s":"Enable timely, consistent and controlled alerts, stakeholder communication, media response and communication-system testing.","e":"Notification procedures; stakeholder and emergency-service contacts; media protocols; message templates; communication logs; tests and exercise records."},
    {"n":"8.4.3.2","c":"8","q":"Where applicable, are threat advisories and national or regional alert systems integrated with the organisation's warning arrangements?","s":"Consider relevant external warning and advisory systems and define how they trigger organisational action.","e":"External alert subscriptions; monitoring responsibilities; trigger matrix; escalation evidence; tests or examples of advisories acted upon."},
    {"n":"8.4.4.1","c":"8","q":"Are business continuity plans and procedures documented and maintained for use during disruption?","s":"Provide controlled, accessible plans capable of guiding timely continuity response.","e":"Approved plans; plan inventory; owners; review schedule; availability at primary and alternate locations; offline access."},
    {"n":"8.4.4.2","c":"8","q":"Do the plans collectively establish actions, time frames, monitoring, communication, dependencies and processes for standing down?","s":"Ensure the plan set collectively covers response, continuity, recovery, coordination, communications and transition from the incident.","e":"Cross-plan mapping; action timelines; performance monitoring; dependency arrangements; communications; stand-down and transition criteria."},
    {"n":"8.4.4.3","c":"8","q":"Does each plan state its purpose, scope, objectives, activation criteria, roles, actions, information needs, communications and interdependencies?","s":"Make every plan sufficiently complete and usable by its intended team under disruptive conditions.","e":"Sampled plan content; checklists; role and contact data; decision authorities; information flows; communication requirements; dependency references."},
    {"n":"8.4.5","c":"8","q":"Are documented processes maintained to restore and return activities from temporary continuity measures to normal operations?","s":"Plan controlled recovery, restoration, backlog management and return to business as usual.","e":"Recovery and restoration procedures; return criteria; data reconciliation; backlog plans; safety and quality checks; handback approvals; lessons captured."},
    {"n":"8.5","c":"8","q":"Is there an exercise programme that validates plans over time, uses realistic scenarios and objectives, produces formal reports and drives improvement?","s":"Exercise continuity arrangements individually and collectively at planned intervals and after significant change without creating unacceptable risk.","e":"Multi-year exercise programme; objectives and scenarios; participant records; observations; after-action reports; corrective actions; re-test and effectiveness evidence."},
    {"n":"8.6","c":"8","q":"Are business continuity documentation and capabilities evaluated through exercises, reviews, incident learning and performance evaluation?","s":"Evaluate suitability, adequacy and effectiveness at planned intervals and after incidents or significant changes, and act on weaknesses.","e":"Capability evaluations; plan reviews; supplier capability checks; post-incident reviews; BIA and strategy validation; improvement actions and approvals."},

    {"n":"9.1","c":"9","q":"Has the organisation determined what BCMS performance and effectiveness will be monitored, measured, analysed and evaluated, including methods, timing and responsibility?","s":"Use valid monitoring and evaluation methods and retain evidence of results.","e":"Performance framework; indicators and thresholds; monitoring schedule; data owners; analysis; trend reports; evaluation conclusions; retained results."},
    {"n":"9.2.1","c":"9","q":"Are internal audits conducted at planned intervals to determine whether the BCMS conforms to organisational and ISO 22301 requirements and is effectively implemented?","s":"Provide objective information on conformity and effective implementation and maintenance.","e":"Completed audit reports; criteria and scope; evidence samples; findings; auditor competence and independence; follow-up records."},
    {"n":"9.2.2","c":"9","q":"Is the internal audit programme risk-based, objective, impartial, reported to relevant management and followed by timely correction and corrective action?","s":"Plan and control audit frequency, methods, responsibilities, criteria, scope, reporting and follow-up.","e":"Audit programme; risk rationale; auditor selection; plans; reports to management; corrections; corrective actions; closure and effectiveness verification."},
    {"n":"9.3.1","c":"9","q":"Does top management review the BCMS at planned intervals for continuing suitability, adequacy and effectiveness?","s":"Use management review as an accountable decision process for BCMS performance and direction.","e":"Management review schedule; attendance; agenda; input papers; minutes; decisions; actions and follow-up."},
    {"n":"9.3.2","c":"9","q":"Does management review consider all required inputs, including previous actions, changes, performance, audit, objectives, incidents, risks, opportunities and improvement?","s":"Provide top management with complete, reliable and decision-ready BCMS information.","e":"Management review pack covering required inputs; trends; exercise and incident results; stakeholder changes; resource and risk information; action status."},
    {"n":"9.3.3","c":"9","q":"Do management review outputs include decisions on improvement and BCMS changes, with retained evidence and communication to relevant interested parties?","s":"Record, assign and communicate management decisions and actions arising from review.","e":"Approved minutes; improvement and change decisions; owners, resources and dates; communications; action tracking; retained review results."},

    {"n":"10.1.1","c":"10","q":"Does the organisation determine and implement opportunities to improve the suitability, adequacy and effectiveness of the BCMS?","s":"Use performance, assurance, incidents and exercises to identify and implement necessary improvement.","e":"Improvement register; trend analysis; lessons; prioritisation; implemented changes; benefits and effectiveness evaluations."},
    {"n":"10.1.2","c":"10","q":"When nonconformity occurs, does the organisation control and correct it, address consequences, determine causes and extent, implement action and verify effectiveness?","s":"Apply proportionate correction and root-cause corrective action that prevents recurrence and updates the BCMS where necessary.","e":"Nonconformity records; immediate corrections; consequence control; root cause and extent review; action plans; effectiveness verification; BCMS changes."},
    {"n":"10.1.3","c":"10","q":"Is documented information retained on nonconformities, actions taken and corrective-action results?","s":"Retain traceable evidence of the issue, response and effectiveness outcome.","e":"Controlled finding and corrective-action records; approvals; evidence attachments; verification results; closure authority and audit trail."},
    {"n":"10.2","c":"10","q":"Does the organisation continually improve the suitability, adequacy and effectiveness of the BCMS using qualitative and quantitative measures?","s":"Demonstrate sustained improvement of the management system and continuity capability.","e":"Improvement trends; maturity reviews; objective performance; exercise progression; reduced vulnerabilities; management decisions; verified benefits."}
  ]
  $requirements$::jsonb) as x(n text, c text, r text, q text, s text, e text)
)
insert into public.assessment_questions
  (standard, question_number, clause, clause_reference, question, requirement_summary,
   assessor_guidance, interview_questions, objective_evidence, sampling_guidance,
   conformity_criteria, minor_nc_guidance, major_nc_guidance, management_focus,
   active, display_order)
select
  'ISO 22301:2019', n, c, coalesce(r,n), q, s,
  'Test both documented design and operational implementation. Trace the requirement through ownership, decisions, representative records and demonstrated results; do not accept a document alone as proof of capability.',
  'Who is accountable for this requirement?|How is it implemented across the full BCMS scope?|What recent evidence shows that it works during normal conditions and disruption?|What weakness or change has management acted upon?',
  e,
  case when c = '8' then 'Sample priority products and services, more than one disruption scenario, relevant sites or teams, critical dependencies and at least one recent exercise or incident record where available.' else 'Sample across relevant functions, locations, responsible roles and reporting periods. Follow one record from decision through implementation and effectiveness review.' end,
  'Current, approved and scope-wide evidence demonstrates that the requirement is implemented, understood and effective, with responsibilities, outputs, review and improvement traceable.',
  'A limited or isolated lapse exists that does not indicate systemic failure or materially undermine continuity capability.',
  'The requirement is absent, substantially ineffective or systemically uncontrolled, or the weakness creates significant doubt that priority products and services can be continued or recovered within approved time frames.',
  case when c = '8' then 'Challenge whether arrangements can work with realistic loss of people, premises, technology, information, utilities or key suppliers—not merely whether a plan exists.' else 'Confirm that leaders receive reliable information, make explicit decisions, provide resources and verify that the intended result is achieved.' end,
  true,
  row_number() over (order by string_to_array(regexp_replace(n, '[a-z]', '', 'g'), '.')::int[])::int
from requirements;

do $profile$
declare
  profile_id uuid;
begin
  update public.scoring_profiles set active = false where standard = 'ISO 22301:2019';
  insert into public.scoring_profiles (standard, profile_name, version_label, active)
  values ('ISO 22301:2019', 'RPG ISO 22301 evidence-led readiness', '2019 v1', true)
  returning id into profile_id;

  insert into public.scoring_profile_clauses (scoring_profile_id, clause, weight)
  values
    (profile_id, '4', 10),
    (profile_id, '5', 10),
    (profile_id, '6', 10),
    (profile_id, '7', 10),
    (profile_id, '8', 35),
    (profile_id, '9', 15),
    (profile_id, '10', 10);
end
$profile$;

