import Link from "next/link";
import {redirect} from "next/navigation";
import BCPHazardScenarioAssessment from "../../../../components/BCPHazardScenarioAssessment";
import {createClient} from "../../../../lib/supabase/server";

export const metadata={title:"BCP Hazard Scenario Risk Assessment | RPG Excellence"};
export const dynamic="force-dynamic";
const clean=value=>String(value??"").trim();
const parseArray=(fd,name)=>{try{const value=JSON.parse(clean(fd.get(name))||"[]");return Array.isArray(value)?value:[]}catch{return []}};
const within=(value,min,max,fallback)=>{const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback};
const riskMetrics=r=>{const impact=Math.max(...Object.values(r?.impact||{}).map(Number),1),likelihood=within(r?.likelihood,1,5,1),effectiveness=within(r?.controlEffectiveness,0,100,0),residualLikelihood=Math.max(1,Math.ceil(likelihood*(1-effectiveness/100)));return{impact,likelihood,inherent:impact*likelihood,residualLikelihood,residual:impact*residualLikelihood}};

async function saveHazards(_previousState,fd){
 "use server";
 const s=await createClient(),{data:{user}}=await s.auth.getUser();
 if(!user)redirect("/portal/login?next=/portal/business-continuity/hazard-scenarios");
 const{data:org}=await s.from("organizations").select("id").eq("owner_id",user.id).order("created_at").limit(1).maybeSingle();
 if(!org)return{error:"Create an organisation before starting Module 5."};
 const t=name=>clean(fd.get(name)),id=t("assessment_id"),intent=t("intent");let existing=null;
 if(id){const{data}=await s.from("bcp_hazard_assessments").select("*").eq("id",id).eq("organization_id",org.id).eq("owner_id",user.id).maybeSingle();existing=data;if(!existing)return{error:"This Module 5 assessment could not be found."}}
 if(intent==="archive"){if(!existing)return{error:"Only an existing assessment can be archived."};const{error}=await s.from("bcp_hazard_assessments").update({status:"archived",updated_at:new Date().toISOString()}).eq("id",existing.id).eq("owner_id",user.id);if(error)return{error:error.message};redirect("/portal/business-continuity")}
 const profileId=t("site_profile_id"),contextId=t("context_assessment_id"),roleId=t("role_assessment_id");
 const [{data:profile},{data:context},{data:role}]=await Promise.all([
  profileId?s.from("bcp_site_profiles").select("*").eq("id",profileId).eq("organization_id",org.id).neq("status","archived").maybeSingle():{data:null},
  contextId?s.from("bcp_context_assessments").select("*").eq("id",contextId).eq("organization_id",org.id).neq("status","archived").maybeSingle():{data:null},
  roleId?s.from("bcp_role_assessments").select("*").eq("id",roleId).eq("organization_id",org.id).neq("status","archived").maybeSingle():{data:null}
 ]);
 const participants=parseArray(fd,"participants"),risks=parseArray(fd,"scenario_assessments").map(r=>({...r,calculated:riskMetrics(r)}));
 const checks=[Boolean(profile),participants.length>0,risks.length>0,risks.every(r=>r.name&&r.description&&r.affectedProcesses?.length),risks.every(r=>r.existingControls?.length&&r.owner),risks.every(r=>r.treatment&&r.decisionRationale&&(r.calculated.residual<6||r.actions?.length))];
 const completion=Math.round(checks.filter(Boolean).length/checks.length*100);
 if(["review","approve"].includes(intent)&&!checks.every(Boolean))return{error:"Complete the linked profile, participants, scenario selection, inherent analysis, control ownership, and treatment rationale/actions before submission."};
 if(intent==="approve"&&profile?.status!=="approved")return{error:"Approve the linked Module 1 Site Profile before approving Module 5."};
 if(intent==="approve"&&context&&context.status!=="approved")return{error:"The linked Module 3 Context Assessment must be approved first."};
 if(intent==="approve"&&role&&role.status!=="approved")return{error:"The linked Module 4 Roles Assessment must be approved first."};
 const reviewer=t("reviewer_name"),comment=t("review_comment");if(intent==="approve"&&!reviewer)return{error:"Record the competent reviewer or approver."};
 const now=new Date().toISOString(),currentVersion=Number(existing?.version)||1,editingApproved=existing?.status==="approved"&&intent!=="approve",version=editingApproved?currentVersion+1:currentVersion,status=intent==="approve"?"approved":intent==="review"?"ready_for_review":"draft";
 const data={owner_id:user.id,organization_id:org.id,site_profile_id:profile?.id||null,context_assessment_id:context?.id||null,role_assessment_id:role?.id||null,site_profile_version:profile?.version||null,context_assessment_version:context?.version||null,role_assessment_version:role?.version||null,source_snapshot:{profile,context,role},assessment_title:t("assessment_title")||"BC risk assessment - hazard scenarios",participants,operational_description:t("operational_description"),scenario_screening:risks.map(r=>({id:r.id,name:r.name,category:r.category})),scenario_assessments:risks,methodology:{impactMethod:"Highest credible impact dimension",inherentFormula:"Impact x likelihood",residualMethod:"Control effectiveness adjusts likelihood",scale:"5 x 5",bands:{low:"1-5",moderate:"6-11",high:"12-19",critical:"20-25"}},review_frequency:t("review_frequency")||"Semi-annually",next_review_date:t("next_review_date")||null,completion_percent:completion,status,version,prepared_by:existing?.prepared_by||user.email||"Account owner",reviewed_by:intent==="approve"?reviewer:null,reviewed_at:intent==="approve"?now:null,review_comment:comment||null,approved_by:intent==="approve"?reviewer:null,approved_at:intent==="approve"?now:null,updated_at:now};
 if(editingApproved){const{error}=await s.from("bcp_hazard_assessment_versions").insert({assessment_id:existing.id,organization_id:org.id,owner_id:user.id,version:currentVersion,status:existing.status,snapshot:existing,change_reason:"Approved version superseded"});if(error)return{error:error.message}}
 let savedId=existing?.id,error;if(existing)({error}=await s.from("bcp_hazard_assessments").update(data).eq("id",existing.id).eq("owner_id",user.id));else{const result=await s.from("bcp_hazard_assessments").insert({...data,assessment_reference:`BCP-HZ-${new Date().getUTCFullYear()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`}).select("id").single();savedId=result.data?.id;error=result.error}if(error)return{error:error.message};
 if(intent==="approve"){const{error:versionError}=await s.from("bcp_hazard_assessment_versions").upsert({assessment_id:savedId,organization_id:org.id,owner_id:user.id,version,status,snapshot:{...data,id:savedId},change_reason:comment||"Controlled approval"},{onConflict:"assessment_id,version"});if(versionError)return{error:versionError.message}}
 if(intent==="continue")redirect(`/portal/business-continuity/hazard-scenarios?id=${savedId}&step=${within(t("next_step"),0,5,0)}`);redirect(`/portal/business-continuity/hazard-scenarios?id=${savedId}&step=5`);
}

export default async function HazardScenarioPage({searchParams}){const params=await searchParams,s=await createClient(),{data:{user}}=await s.auth.getUser();if(!user)redirect("/portal/login?next=/portal/business-continuity/hazard-scenarios");const{data:org}=await s.from("organizations").select("id,name").eq("owner_id",user.id).order("created_at").limit(1).maybeSingle();let profiles=[],contexts=[],roles=[],initial=null;if(org){({data:profiles=[]}=await s.from("bcp_site_profiles").select("*").eq("organization_id",org.id).neq("status","archived").order("updated_at",{ascending:false}));({data:contexts=[]}=await s.from("bcp_context_assessments").select("*").eq("organization_id",org.id).neq("status","archived").order("updated_at",{ascending:false}));({data:roles=[]}=await s.from("bcp_role_assessments").select("*").eq("organization_id",org.id).neq("status","archived").order("updated_at",{ascending:false}));if(params?.new!=="1"){let query=s.from("bcp_hazard_assessments").select("*").eq("organization_id",org.id).neq("status","archived");if(params?.id)query=query.eq("id",params.id);({data:initial}=await query.order("updated_at",{ascending:false}).limit(1).maybeSingle())}}return <main style={{minHeight:"100vh",padding:"26px 2vw 80px",background:"#edf3f8",fontFamily:"Arial,sans-serif"}}><div style={{maxWidth:1780,margin:"auto"}}><header style={{display:"flex",justifyContent:"space-between",gap:20,marginBottom:20}}><div><small style={{color:"#6845d1",fontWeight:900,letterSpacing:".1em"}}>BCP HUB · MODULE 5 · ISO 22301 CLAUSE 8.2.3</small><h1 style={{margin:"7px 0",color:"#071d3a",fontSize:42}}>Risk Assessment - Hazard Scenarios</h1><p style={{margin:0,color:"#62788e"}}>Screen credible disruption threats, quantify inherent and residual risk, and control treatment decisions.</p></div><div style={{display:"flex",gap:8}}><Link href="/portal/business-continuity/hazard-scenarios?new=1" style={{padding:"11px 14px",borderRadius:8,background:"#315fe6",color:"#fff",textDecoration:"none",fontWeight:850}}>+ New assessment</Link><Link href="/portal/business-continuity" style={{padding:"11px 14px",border:"1px solid #c5d3e0",borderRadius:8,background:"#fff",color:"#173b60",textDecoration:"none",fontWeight:850}}>← BCP Hub</Link></div></header><BCPHazardScenarioAssessment action={saveHazards} profiles={profiles} contexts={contexts} roles={roles} initial={initial} organisationName={org?.name||""} startStep={params?.step||0}/></div></main>}
